const PRODUCTS = [
  {
    "asin": "B0DCLXRD5X",
    "title": "Fogão Elétrico Portátil Cooktop Elgin Double Cook 2 Bocas - 220V",
    "image": "https://m.media-amazon.com/images/I/41z7d-LlVEL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 79.9,
    "price_original": 159.9,
    "discount_percentage": 50.0,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.5,
    "qtd_avaliacoes": 1281,
    "coupon_code": null,
    "description": "<ul><li>Portátil e Compacto: Ideal para cozinhas pequenas, apartamentos, campings e áreas gourmets, facilitando o transporte e o armazenamento sem ocupar muito espaço.</li><li>Voltagem 220V: Projetado especificamente para redes elétricas de 220 volts, garantindo compatibilidade e desempenho seguro onde a voltagem padrão é esta.</li><li>Versátil e Eficiente: Equipado com duas bocas para o preparo simultâneo de diferentes pratos, oferecendo praticidade para refeições rápidas e variadas.</li></ul>",
    "informacoes_produto": {
      "Características especiais": "Controle de temperatura, Leve, Portátil",
      "Número de elementos de aquecimento": "2",
      "Potência": "2000 watts",
      "Tipo de controles": "Puxador",
      "Voltagem": "220 Volts",
      "Elemento de aquecimento": "Indução",
      "Fonte de energia": "Energia elétrica",
      "Cor": "Preto",
      "Material": "Liga de aço",
      "Dimensões do item P x L x A": "6,4P x 43L x 23A centímetros",
      "Peso do item": "1,2 Quilogramas",
      "Nome da marca": "Elgin",
      "Componentes incluídos": "01 Fogão com duas placas de aquecimento, 04 Suportes para estabilização do aparelho, 01 Manual do Usuário",
      "Ano de fabricação": "1900",
      "Fabricante": "Elgin",
      "Descrição da garantia": "90 dias",
      "Número da peça": "42FOG0202000",
      "Número do modelo": "42FOG0202000",
      "Nome do Tipo de Produto": "Fogão Elétrico Portátil",
      "ASIN": "B0DCLXRD5X",
      "Marca": "Elgin",
      "Elementos de aquecimento": "2"
    },
    "affiliate_url": "https://www.amazon.com.br/El%C3%A9trico-Port%C3%A1til-Cooktop-Elgin-Double/dp/B0DCLXRD5X/ref=zg_bs_g_appliances_d_sccl_1/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:56:47.000Z",
    "spotlight": false
  },
  {
    "asin": "B0B3SJ345V",
    "title": "SUGGAR DEPURADOR DE AR SLIM 60CM 3 VEL. PRETO 110V DPS161PT",
    "image": "https://m.media-amazon.com/images/I/41q3C2LevmL._AC_SL1200_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 336.98,
    "price_original": 449,
    "discount_percentage": 24.0,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.6,
    "qtd_avaliacoes": 5347,
    "coupon_code": null,
    "description": "<ul><li>Depurador de ar</li></ul>",
    "informacoes_produto": {
      "Características especiais": "Coletor de óleo embutido",
      "Capacidade do fluxo de ar": "430 Metros cúbicos por hora",
      "Nível de ruído": "65 Decibéis",
      "Tipo de montagem": "Montagem na parede",
      "Tipo de controles": "Botão de pressão",
      "Voltagem": "110 Volts",
      "Tipo de filtro": "Malha e Carvão Ativado",
      "Tipo de ventilação": "Ductless/Recirculating",
      "Cor": "preto",
      "Tipo de acabamento": "Pintado",
      "Formato do item": "Parede, Insert",
      "Dimensões do item P x L x A": "48P x 60L x 8,5A centímetros",
      "Peso do item": "5,12 Quilogramas",
      "Nome da marca": "Suggar",
      "Componentes incluídos": "Manual de instruções",
      "Número do modelo": "DPS161PT",
      "Fabricante": "Suggar",
      "Número da peça": "DPS161PT",
      "País de origem": "Brasil",
      "Nome do Tipo de Produto": "Depurador de Ar",
      "Descrição da garantia": "1 ano de garantia",
      "ASIN": "B0B3SJ345V",
      "Material": "Liga de aço",
      "Marca": "Suggar",
      "Dimensões do produto": "48P x 60L x 8,5A centímetros"
    },
    "affiliate_url": "https://www.amazon.com.br/SUGGAR-DEPURADOR-SLIM-PRETO-DPS161PT/dp/B0B3SJ345V/ref=zg_bs_g_appliances_d_sccl_2/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:56:47.000Z",
    "spotlight": false
  },
  {
    "asin": "B0FP1251TD",
    "title": "Suporte com Rodinhas Movel Ajustável Telescópico para Geladeira Fogão Máquina de Lavar Móveis Pesados até 200kgs Base Antider",
    "image": "https://m.media-amazon.com/images/I/41iY1Zn43VL._AC_SL1072_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 29.89,
    "price_original": 32.9,
    "discount_percentage": 9.0,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.2,
    "qtd_avaliacoes": 676,
    "coupon_code": null,
    "description": "<ul><li>✅ Suporte reforçado que aguenta até 200kg com segurança e estabilidade</li><li>🔄 Ajustável de 45cm a 70cm – ideal para diversos eletrodomésticos e móveis pesados</li><li>🔇 Rodízios silenciosos que deslizam com suavidade, sem riscos ao piso</li><li>🛡️ Base antiderrapante para máxima aderência e proteção do chão</li><li>💪 Estrutura resistente com pintura antiferrugem – maior durabilidade</li><li>🧰 Pronto para usar: sem montagem complicada, economia de tempo</li><li>🧼 Facilita a limpeza embaixo de geladeiras, fogões e lavadoras</li><li>🏡 Ideal para casas, apartamentos, lavanderias e áreas de serviço</li><li>⚙️ Compacto, funcional e versátil – otimiza seu espaço com eficiência</li><li>🛒 Essencial para quem busca praticidade, organização e mobilidade</li></ul>",
    "informacoes_produto": {
      "Fabricante": "‎Importado",
      "Certificação": "‎Não aplicável",
      "Cor": "‎Prata",
      "Tipo de fonte de energia": "‎Não aplicável",
      "Número de produtos": "‎1",
      "Componentes incluídos": "‎Suporte de rodinhas",
      "Comprimento": "‎45 centímetros",
      "Largura": "‎4 centímetros",
      "Altura": "‎5 centímetros",
      "Modelo": "‎001",
      "Número do modelo": "‎001",
      "Dimensões do produto": "‎45 x 4 x 5 cm; 980 g",
      "ASIN": "‎B0FP1251TD",
      "Marca": "‎Genérico",
      "Dimensões do pacote": "49.9 x 11.8 x 5.8 centímetros",
      "Disponível para compra desde": "28 agosto 2025"
    },
    "affiliate_url": "https://www.amazon.com.br/Ajust%C3%A1vel-Telesc%C3%B3pico-Antiderrapante-Deslizante-Silencioso/dp/B0FP1251TD/ref=zg_bs_g_appliances_d_sccl_3/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:56:47.000Z",
    "spotlight": false
  },
  {
    "asin": "B0B3SJ8YLP",
    "title": "SUGGAR DEPURADOR DE AR SLIM 80CM 3 VEL. PRETO 220V DPS182PT",
    "image": "https://m.media-amazon.com/images/I/41reXjYlagL._AC_SL1200_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 378,
    "price_original": 2899,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.5,
    "qtd_avaliacoes": 2762,
    "coupon_code": null,
    "description": "<ul><li>Depurador de ar</li></ul>",
    "informacoes_produto": {
      "Características especiais": "Dupla filtragem",
      "Capacidade do fluxo de ar": "420 Metros cúbicos por hora",
      "Nível de ruído": "65 Decibéis",
      "Tipo de montagem": "Montagem na parede",
      "Tipo de controles": "Interface física",
      "Voltagem": "220 Volts",
      "Número de velocidades": "3",
      "Tipo de filtro": "tela de alumínio lavável, filtro de carvão ativado",
      "Tipo de ventilação": "Ductless/Recirculating",
      "Cor": "preto",
      "Tipo de acabamento": "Preto Revestido em Pó",
      "Formato do item": "Montagem na parede",
      "Dimensões do item P x L x A": "48P x 80L x 8,5A centímetros",
      "Peso do item": "5,1 Quilogramas",
      "Nome da marca": "Suggar",
      "Componentes incluídos": "Manual de instruções",
      "Número do modelo": "DPS182PT",
      "Fabricante": "Suggar",
      "Número da peça": "DPS182PT",
      "País de origem": "Brasil",
      "Contagem de unidades": "1 Count",
      "Nome do Tipo de Produto": "Depurador de Ar",
      "Descrição da garantia": "1 ano de garantia",
      "ASIN": "B0B3SJ8YLP",
      "Material": "Liga de aço",
      "Marca": "Suggar",
      "Dimensões do produto": "48P x 80L x 8,5A centímetros"
    },
    "affiliate_url": "https://www.amazon.com.br/SUGGAR-DEPURADOR-SLIM-PRETO-DPS182PT/dp/B0B3SJ8YLP/ref=zg_bs_g_appliances_d_sccl_4/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:56:47.000Z",
    "spotlight": true
  },
  {
    "asin": "B0876YDWVC",
    "title": "Dover-Roll Odor Defense Banheiro & Pia Lilás, Rolo com 50 Sacos para Lixo Pure Fresh",
    "image": "https://m.media-amazon.com/images/I/51DjpTGQlFL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 14.99,
    "price_original": 21.22,
    "discount_percentage": 29.0,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 9604,
    "coupon_code": null,
    "description": "<ul><li>Ideal para a cestinha de banheiros e pias</li><li>Com aroma fresco e agradável</li><li>Exclusiva tecnologia Pure Fresh</li><li>Neutraliza os maus odores</li><li>Medidas do saco 34 x 40cm</li></ul>",
    "informacoes_produto": {
      "Capacidade": "8 litros",
      "Contagem de unidades": "50 unidade",
      "Quantidade de itens": "1",
      "Características do material": "Perfumado",
      "Material": "Plástico",
      "Cor": "Lilás",
      "Formato do item": "Sacola",
      "Aroma": "Sem perfume",
      "Nome da marca": "Dover-Roll",
      "Usos recomendados do produto": "Resíduo sanitário",
      "Fabricante": "Engetech Com. Ind. Plast. Ltda",
      "Componentes incluídos": "produto + embalagem",
      "Nome do Tipo de Produto": "Sacos para Lixo",
      "País de origem": "Brasil",
      "ASIN": "B0876YDWVC",
      "Marca": "Dover-Roll",
      "Adequação do controle por rádio": "Resíduo sanitário",
      "Característica do material": "Perfumado"
    },
    "affiliate_url": "https://www.amazon.com.br/Dover-Roll-Defense-Banheiro-Lil%C3%A1s-510022028/dp/B0876YDWVC/ref=zg_bs_g_appliances_d_sccl_5/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:56:47.000Z",
    "spotlight": false
  },
  {
    "asin": "B084R94R4S",
    "title": "Máquina de Lavar Electrolux 11kg Branca Essential Care com Easy Clean e Filtro Fiapos (LES11) - 127V",
    "image": "https://m.media-amazon.com/images/I/41+50Z4TgEL._AC_SL1200_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 1699,
    "price_original": 2368.41,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 658,
    "coupon_code": null,
    "description": "<ul><li>EXCLUSIVO SISTEMA EASY</li><li>CICLO RÁPIDO</li><li>REUSO DE ÁGUA</li><li>FILTRO PEGA FIAPOS</li></ul>",
    "informacoes_produto": {
      "Capacidade": "11 quilogramas",
      "Características especiais": "Ciclo Rápido, Reuso de Água, Easy Clean, Filtro Fiapos",
      "Local do acesso": "Carga superior",
      "Tipo de acabamento": "Branco",
      "Opções de ciclo": "Normal, Pesado, Rápido, Delicado, Enxágue",
      "Tipo de controles": "Botão de pressão",
      "Modo de operação": "Totalmente automático",
      "Voltagem": "110 Volts",
      "Número de ciclos padrão": "10",
      "Tipo de instalação": "Independente",
      "Dimensões do item P x L x A": "71,1P x 61,7L x 104,5A centímetros",
      "Peso do item": "40,5 Quilogramas",
      "Profundidade do item": "67,6 centimeters",
      "Material": "Metal",
      "Material do tambor do aparelho de lavagem de roupa": "Aço inoxidável",
      "Nome da marca": "Electrolux",
      "Usos recomendados do produto": "Residencial",
      "Nome do modelo": "Electrolux LES11 Essential Care",
      "Componentes incluídos": "1 Máquina de Lavar 11kg Electrolux Essential Care Silenciosa com Easy Clean e Filtro Fiapos (LES11)",
      "Fabricante": "Electrolux",
      "Número do modelo": "LES11",
      "Número da peça": "LES11",
      "Descrição da garantia": "12 meses",
      "Nome do Tipo de Produto": "Lavadora Top load",
      "ASIN": "B084R94R4S",
      "Cor": "Branco",
      "Dimensões do produto": "71,1P x 61,7L x 104,5A centímetros",
      "Marca": "Electrolux",
      "Local de acesso": "Carga superior"
    },
    "affiliate_url": "https://www.amazon.com.br/Lavadora-Roupas-Electrolux-LES11-Essencial/dp/B084R94R4S/ref=zg_bs_g_appliances_d_sccl_6/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:56:47.000Z",
    "spotlight": false
  },
  {
    "asin": "B086WWQX1S",
    "title": "Oikos - Kit 3 Sacos para Lavar Roupas Delicadas P,M e G com Zíper | Camisetas, proteção dos tecidos, roupas íntimas, máquina",
    "image": "https://m.media-amazon.com/images/I/61BJhE0GLIL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 19.9,
    "price_original": 25,
    "discount_percentage": 20.0,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.6,
    "qtd_avaliacoes": 4328,
    "coupon_code": null,
    "description": "<ul><li>Com 3 tamanhos diferentes: comportam desde a roupa íntima até roupa de cama, protegendo os tecidos durante a lavagem - principalmente os mais finos e delicados.</li><li>Funcionais: eles mantêm a qualidade das peças e ainda deixam as roupas sem aquelas bolinhas e nem fiapos.</li><li>Multiusos: também são bem legais na hora de organizar a mala de viagem e para proteger aquelas roupas que não são usadas no dia a dia dentro do armário.</li><li>Acabamento no zíper: seu zíper tem um compartimento próprio para não desfiar as roupas enquanto a lavagem acontece na máquina.</li><li>Fácil de limpar: pode ser lavado normalmente na água corrente com sabão, ou na máquina de lavar.</li></ul>",
    "informacoes_produto": {
      "Características especiais": "Acabamento no zíper, Fácil de limpar",
      "Usos recomendados do produto": "Roupas",
      "Tipo de fechamento": "Zíper",
      "Dimensões do item C x L x A": "40C x 50L x 0,3A centímetros",
      "Quantidade de itens": "3",
      "Tamanho": "Tamanho único",
      "Peso do item": "70 Gramas",
      "Número de Conjuntos": "3",
      "Cor": "Branco",
      "Material": "Plástico, Poliéster",
      "Nome da marca": "OIKOS",
      "Contagem de unidades": "3.0 Peça",
      "País de origem": "China",
      "Componentes incluídos": "Conjunto de 3 de Sacos P/M/G para Maquina de Lavar Roupas - Oikos",
      "Nome do Tipo de Produto": "Saco para máquina de lavar",
      "Fabricante": "OIKOS",
      "Número do modelo": "LAV00341BRC",
      "Número da peça": "LAV00341BRC",
      "Descrição da garantia": "90 Dias",
      "ASIN": "B086WWQX1S",
      "Marca": "OIKOS",
      "Dimensões do produto": "40C x 50L x 0,3A centímetros"
    },
    "affiliate_url": "https://www.amazon.com.br/Oikos-conjunto-m%C3%A1quina-roupas-delicadas/dp/B086WWQX1S/ref=zg_bs_g_appliances_d_sccl_7/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:56:47.000Z",
    "spotlight": false
  },
  {
    "asin": "B00HGNXC8Q",
    "title": "Máquina de Lavar Panasonic 15kg Branca Função Vanish NA-F150B1W 127v",
    "image": "https://m.media-amazon.com/images/I/61gXZ2VqfdL._AC_SL1500_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 1926.77,
    "price_original": 2299,
    "discount_percentage": 16.0,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.6,
    "qtd_avaliacoes": 222,
    "coupon_code": null,
    "description": "<ul><li>Lavadora 15kg com a melhor lavagem e o menor consumo de água da categoria, segundo o Inmetro</li><li>Cor branca e voltagem de 127V, adequada para uso doméstico</li><li>Melhor lavagem e menor consumo de água da categoria, segundo o Inmetro</li></ul>",
    "informacoes_produto": {
      "Capacidade": "15 quilogramas",
      "Características especiais": "Sistema Ciclone de lavagem sem agitador, Smartsense",
      "Local do acesso": "Carga frontal",
      "Tipo de acabamento": "Branca",
      "Opções de ciclo": "Vanish, Vanish Branco mais Branco",
      "Modo de operação": "Totalmente automático",
      "Voltagem": "127 Volts",
      "Tipo de instalação": "Independente",
      "Dimensões do item P x L x A": "69P x 60L x 105A centímetros",
      "Material do tambor do aparelho de lavagem de roupa": "Aço inoxidável",
      "Cor": "Branca",
      "Nome da marca": "Panasonic",
      "Usos recomendados do produto": "Residencial",
      "Componentes incluídos": "Mangueira de drenagem",
      "Fabricante": "PANASONIC",
      "Número do modelo": "NA-F150B1WA",
      "Número da peça": "1",
      "Descrição da garantia": "12 meses",
      "Nome do Tipo de Produto": "MAQUINA DE LAVAR",
      "País de origem": "Brasil",
      "ASIN": "B00HGNXC8Q",
      "Dimensões do produto": "69P x 60L x 105A centímetros",
      "Marca": "Panasonic",
      "Local de acesso": "Carga frontal"
    },
    "affiliate_url": "https://www.amazon.com.br/Panasonic-M%C3%A1quina-Lavar-Branca-NA-F150B1W/dp/B00HGNXC8Q/ref=zg_bs_g_appliances_d_sccl_8/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:56:47.000Z",
    "spotlight": false
  },
  {
    "asin": "B09B8VWZRG",
    "title": "Máquina de Lavar 17kg Electrolux Essential Care com Cesto Inox, Jet&Clean e Ultra Filter (LED17)",
    "image": "https://m.media-amazon.com/images/I/41jXZmfuQoL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 2199,
    "price_original": 4449,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 410,
    "coupon_code": null,
    "description": "<ul><li>ÚNICO³ COM TECNOLOGIA JET&amp;CLEAN</li><li>ULTRA FILTER PEGA FIAPOS</li><li>SISTEMA DE LAVAGEM COM CICLOS RÁPIDOS</li><li>PROGRAMA SUPER SILENCIOSO</li><li>FUNÇÃO LIMPEZA DE CESTO</li></ul>",
    "informacoes_produto": {
      "Capacidade": "17 quilogramas",
      "Características especiais": "Alta eficiência",
      "Local do acesso": "Carga superior",
      "Tipo de acabamento": "Aço inoxidável",
      "Opções de ciclo": "Ciclos Rápidos, Super Silencioso",
      "Tipo de controles": "Botões e volante",
      "Modo de operação": "Totalmente automático",
      "Voltagem": "110 Volts",
      "Número de ciclos padrão": "11",
      "Entrada de interface humana": "Botões, Seletor",
      "Tipo de instalação": "Independente",
      "Opções de dosador da máquina de lavar": "2 compartimentos (detergente e amaciante)",
      "Número de programas": "11",
      "Dimensões do item P x L x A": "66,2P x 105,2L x 59,3A centímetros",
      "Peso do item": "46 Quilogramas",
      "Profundidade do item": "66,2 centimeters",
      "Cor": "Branco",
      "Nome da marca": "Electrolux",
      "Usos recomendados do produto": "Residencial",
      "Nome do modelo": "LED17",
      "Componentes incluídos": "1 Máquina de Lavar 17kg Electrolux Essential Care com Cesto Inox, Jet&amp;Clean e Ultra Filter (LED17)",
      "Fabricante": "Electrolux",
      "Número do modelo": "LED17",
      "Número da peça": "LED17",
      "Descrição da garantia": "12 meses",
      "Nome do Tipo de Produto": "Lavadora Top load",
      "ASIN": "B09B8VWZRG",
      "Material": "aço inoxidável",
      "Material do tambor do aparelho de lavagem de roupa": "aço inoxidável",
      "Dimensões do produto": "66,2P x 105,2L x 59,3A centímetros",
      "Marca": "Electrolux",
      "Local de acesso": "Carga superior"
    },
    "affiliate_url": "https://www.amazon.com.br/M%C3%A1quina-Lavar-Electrolux-Essential-Filter/dp/B09B8VWZRG/ref=zg_bs_g_appliances_d_sccl_9/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:56:47.000Z",
    "spotlight": true
  },
  {
    "asin": "B08NWQHGR4",
    "title": "Artist Unknown - Pacote com 4 Cal�os de Borracha Redondos Pretos para Elevar e Estabilizar Lavadora, Secadora, Geladeira ou O",
    "image": "https://m.media-amazon.com/images/I/61nbiJ9iyTL._AC_SL1500_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 14.49,
    "price_original": 23.99,
    "discount_percentage": 39.0,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.2,
    "qtd_avaliacoes": 3241,
    "coupon_code": null,
    "description": "<ul><li>Bases de borracha: antivibração, anti-deslocamento, para evitar arranhões no chão e eliminar o ruído.</li><li>Material de alta qualidade: feito de borracha e plástico de alta qualidade, duráveis em ambientes úmidos ou rústicos;</li><li>Ao elevar sua máquina até 3,5 a 8,5 cm (como você escolher), o seu problema é resolvido, insetos não têm onde se esconder e acaba a sujeira embaixo.</li><li>Adequado para lavadora, secadora, geladeira ou outros eletrodomésticos ou móveis que precisam de altura elevada e estabilidade.</li><li>Fácil de instalar. Reduz os custos de manutenção de lavadoras e secadoras e reduz o ruído.</li></ul>",
    "informacoes_produto": {
      "Nome da marca": "Unknown",
      "Número de identificação de comércio internacional": "00743910819538",
      "UPC": "743910819538",
      "Contagem de unidades": "4 metro",
      "Fabricante": "#N/A",
      "Número da peça": "10be1afc004b0a873ec135670975a0d2",
      "ASIN": "B08NWQHGR4",
      "Superfície Recomendada": "duras, laminado, azulejo e alfombra",
      "Usos recomendados do produto": "móveis pesados sobre diferentes tipos de pisos",
      "Tipo de fixação": "Removível",
      "Quantidade de itens": "4",
      "Número de peças": "4",
      "Cor": "Cinza, 3,5 cm",
      "Formato do item": "Redondo",
      "Material": "Plástico",
      "Material do cabo": "Borracha",
      "Marca": "Unknown",
      "Recomendação de superfície": "duras, laminado, azulejo e alfombra",
      "Forma": "Redondo"
    },
    "affiliate_url": "https://www.amazon.com.br/Artist-Estabilizar-Eletrodom%C3%A9sticos-Antivibra%C3%A7%C3%A3o-Anti-Deslocamento/dp/B08NWQHGR4/ref=zg_bs_g_appliances_d_sccl_10/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:56:47.000Z",
    "spotlight": false
  },
  {
    "asin": "B0FLQJJ47J",
    "title": "Lava-Louças Electrolux 14 Serviços Inox com Programa Lava e Seca 220v LS14E",
    "image": "https://m.media-amazon.com/images/I/41+T6Xe5XKL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 2899,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.6,
    "qtd_avaliacoes": 53,
    "coupon_code": null,
    "description": "<ul><li>Lava-Louça Electrolux 14 Serviços Inox com Programa Lava e Seca 50' (LS14E)</li></ul>",
    "informacoes_produto": {
      "Tipo de instalação": "Embutido",
      "Capacidade": "10,9 litros",
      "Características especiais": "Programa Lava &amp; Seca, Programa Eco, Higienizar Louça 70°C, Display Digital com Controle do Tempo, Adiar Início, Função de Secagem Extra, Programa Delicado, Meia Carga, Express 30",
      "Tipo de controles": "Toque",
      "Fator de forma": "Autônomo",
      "Voltagem": "220 Volts",
      "Opções de ciclo": "Lava &amp; Seca, Eco, Delicado, Meia Carga, Express 30",
      "Número de ciclos de opções": "9",
      "Dimensões do item P x L x A": "64,5P x 64,5L x 87,1A centímetros",
      "Peso do item": "41,5 Quilogramas",
      "Cor": "inox",
      "Nome da marca": "Electrolux",
      "Componentes incluídos": "Cabo de alimentação",
      "Usos recomendados do produto": "Louças de uso diário, panelas, utensílios e louças delicadas",
      "Número do modelo": "LS14E",
      "Fabricante": "ELECTROLUX",
      "Número da peça": "LS14E",
      "Descrição da garantia": "12 meses com o fabricante",
      "ASIN": "B0FLQJJ47J",
      "Avaliação por estrelas do BEE": "Não",
      "Marca": "Electrolux",
      "Dimensões do produto": "64,5P x 64,5L x 87,1A centímetros"
    },
    "affiliate_url": "https://www.amazon.com.br/Electrolux-Lava-Lou%C3%A7a-Servi%C3%A7os-Programa-LS14E/dp/B0FLQJJ47J/ref=zg_bs_g_appliances_d_sccl_11/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:56:47.000Z",
    "spotlight": false
  },
  {
    "asin": "B07CZ3R2P8",
    "title": "Refil Filtro Vela Purificador Soft Everest Original",
    "image": "https://m.media-amazon.com/images/I/41XhFbEHcKL._AC_SL1080_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 90.49,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.9,
    "qtd_avaliacoes": 1080,
    "coupon_code": null,
    "description": "<ul><li>Este item é vendido por um vendedor parceiro. O desconto é fornecido pela Amazon.</li><li>Este é um desconto por tempo limitado.</li><li>O desconto não se aplica ao conteúdo digital.</li><li>O desconto é válido enquanto durarem os estoques ou até que seja recusado pela Amazon.</li><li>Os fretes de envio e os impostos podem ser aplicáveis a preços promocionais.</li><li>A Amazon se reserva o direito de modificar ou cancelar o desconto a qualquer momento.</li><li>Se você tiver de devolver algum dos produtos ou conteúdo adquiridos na promoção, o valor a ser reembolsado será o pago, de acordo com nossas políticas de reembolso.</li></ul>",
    "informacoes_produto": {
      "Benefícios do produto": "Remove impurezas e contaminantes",
      "Nome da marca": "SOFT",
      "Quantidade de itens": "1",
      "Número da peça": "111",
      "Fabricante": "Everest",
      "ASIN": "B07CZ3R2P8",
      "Material": "Carvão",
      "Dimensões do item P x L x A": "12P x 30L x 8A centímetros",
      "Peso do item": "600 Gramas",
      "Dimensões do produto": "12P x 30L x 8A centímetros",
      "Peso do produto": "600 Gramas",
      "Vantagens do produto": "Remove impurezas e contaminantes",
      "Marca": "SOFT"
    },
    "affiliate_url": "https://www.amazon.com.br/Refil-Filtro-Purificador-Everest-Original/dp/B07CZ3R2P8/ref=zg_bs_g_appliances_d_sccl_12/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:56:47.000Z",
    "spotlight": false
  },
  {
    "asin": "B0D7NPF9Z2",
    "title": "\"Capa Para Maquina De Lavar Brastemp Eletrolux Consul 07Kg 08Kg 09Kg 10Kg 11Kg12Kg 13Kg 14Kg 15Kg 16Kg 17Kg Impermeável Forra",
    "image": "https://m.media-amazon.com/images/I/61e0+ijy0pL._AC_SL1200_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 39.9,
    "price_original": 49.9,
    "discount_percentage": 20.0,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.4,
    "qtd_avaliacoes": 1480,
    "coupon_code": null,
    "description": "<ul><li>🛡️ Proteção Completa: Garanta a proteção total da sua máquina de lavar com nossa capa de máquina de lavar impermeável, que protege contra poeira, umidade e danos externos. Com ela, você prolonga a vida útil do seu eletrodoméstico, evitando desgastes prematuros e custos adicionais com reparos. Compre agora e tenha a tranquilidade de um equipamento sempre protegido!</li><li>🌧️ Material Impermeável e Forrado: Nossa capa é fabricada com material impermeável de alta qualidade, além de ser forrada internamente e conter elástico traseiro para se ajustar melhor a sua máquina. Isso proporciona uma barreira eficaz contra a umidade, prevenindo danos causados por líquidos e respingos. Ideal para áreas com alta umidade ou para proteger durante a limpeza do ambiente. Proteja sua máquina de lavar em qualquer situação!</li><li>☀️ Proteção UV Avançada: Nossa capa possui tratamento UV, garantindo uma camada adicional de defesa contra os raios solares. Isso é essencial para evitar o desbotamento e o envelhecimento precoce da sua máquina, especialmente em áreas expostas ao sol. Evite danos causados pelo sol e mantenha sua máquina nova por mais tempo!</li><li>🔄 Parte Superior Removível e Prática: A parte superior da capa é removível, facilitando o uso diário da sua máquina de lavar sem comprometer a proteção. Essa funcionalidade permite um acesso fácil e rápido ao tambor e ao painel, tornando o seu dia a dia mais prático. Experimente a conveniência de uma capa que acompanha seu ritmo!</li><li>🌟 Versatilidade para Diversas Marcas e Modelos: Compatível com diversas marcas renomadas como Brastemp, Electrolux, Consul, LG, Samsung e Midea, e capacidades de 07 a 17 Kg. Esta capa é versátil e adapta-se a uma ampla gama de modelos, garantindo proteção universal. Encontre a capa perfeita para sua máquina, adquira já e desfrute da versatilidade! 📏 Disponível em Tamanhos P, M e G: Oferecemos medidas específicas para se ajustar perfeitamente às suas necessidades. Cada tamanho foi projetado para cobrir máquinas de lavar de diferentes capacidades, garantindo um encaixe perfeito e proteção eficiente. Escolha o tamanho ideal para sua máquina e compre agora mesmo!</li><li>MEDIDAS DA CAPA P: Lado Frente: 60cm Largura X 89cm Comprimento Lado Costas: 60cm Largura X 98cm Comprimento Profundidade: 60cm Serve para Maquinas : Brastemp 07 a 09 KG Consul de 07 a 09 KG Eletrolux de 07 a 09 KG Dentre outras marcas e modelos !</li><li>MEDIDAS DA CAPA M: Lado Frente: 64cm Largura X 89cm Comprimento Lado Costas: 64cm Largura X 98cm Comprimento Profundidade: 64cm Serve para Maquinas : Brastemp 10 e 11 KG Consul de 10 a 12 KG Eletrolux de 10 a 12 KG Dentre outras marcas e modelos !</li><li>MEDIDAS DA CAPA G: Lado Frente: 68cm Largura X 89cm Comprimento Lado Costas: 68cm Largura X 98cm Comprimento Profundidade: 68cm Serve para Maquinas : Brastemp 12 e 17 KG Consul de 13 a 17 KG Eletrolux de 13 a 17 KG Dentre outras marcas e modelos !</li><li>🎨 Design Elegante e Funcional: O acabamento perolizado não só confere durabilidade, mas também um toque de elegância à sua lavanderia. Este design sofisticado harmoniza com qualquer decoração, mantendo o ambiente organizado e esteticamente agradável. Renove o visual da sua lavanderia com estilo e funcionalidade, compre agora!</li><li>🔧 Fácil Instalação com Ajuste Perfeito: Com elástico na traseira, a instalação da capa é simples e rápida, proporcionando um ajuste perfeito à sua máquina de lavar. Essa facilidade de uso garante que a capa permaneça firme e segura, sem complicações. Simplifique a proteção da sua máquina com uma instalação descomplicada, compre agora!</li></ul>",
    "informacoes_produto": {
      "Nome da marca": "Neri Shop",
      "Número do modelo": "Capa de máquina Couronil",
      "Número da peça": "Capa de máquina Couronil",
      "Fabricante": "Neri Shop",
      "Contagem de unidades": "1 Unidade",
      "Nome do Tipo de Produto": "Capa Para Máquina De Lavar",
      "Descrição da garantia": "30 Dias",
      "Componentes incluídos": "01 Capa de Máquina de Lavar",
      "ASIN": "B0D7NPF9Z2",
      "Nível de resistência à água": "À prova d'água",
      "Tipo de fechamento": "Elástico",
      "Tipo de alça": "Elástico",
      "Material": "Cloreto de polivinilo (PVC), Poliéster",
      "Cor": "Cinza",
      "Marca": "Neri Shop"
    },
    "affiliate_url": "https://www.amazon.com.br/Capa-Brastemp-Eletrolux-Imperme%C3%A1vel-Resistente/dp/B0D7NPF9Z2/ref=zg_bs_g_appliances_d_sccl_13/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:56:47.000Z",
    "spotlight": false
  },
  {
    "asin": "B0798XT2VK",
    "title": "Protetor De Geladeira ou Freezer Contra Queda Surtos de Energia 127V",
    "image": "https://m.media-amazon.com/images/I/516wjfTaZwL._AC_SL1125_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 45,
    "price_original": null,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.5,
    "qtd_avaliacoes": 5731,
    "coupon_code": null,
    "description": "<ul><li>Protege contra raios e surtos</li><li>Protege contra quedas de energia</li><li>Possui temporizador de 8 minutos</li><li>Evita que o efeito pisca-pisca queima o motor</li><li>religa automaticamente quando a energia normaliza</li></ul>",
    "informacoes_produto": {
      "Fabricante": "‎PW",
      "Número da Peça": "‎205",
      "Certificação": "‎Não aplicável, Não aplicável",
      "Cor": "‎Branco",
      "Material": "‎Componentes eletronicos, Metal, Plástico, cobre, fios",
      "Formato": "‎Retangular",
      "Tipo de fonte de energia": "‎AC",
      "Voltagem": "‎127 Volts",
      "Etiqueta Nacional de Eficiência Energética (ENCE)": "‎A",
      "Potência em watts": "‎1200 watts",
      "Quantidade por pacote": "‎1",
      "Número de produtos": "‎1",
      "Número de furos": "‎1",
      "Usos específicos do produto": "‎residencial, comercial e industrial",
      "Componentes incluídos": "‎1 produto",
      "Baterias inclusas?": "‎Não",
      "Funciona a bateria ou pilha?": "‎Não",
      "Peso": "‎120 Gramas",
      "Comprimento": "‎10 centímetros",
      "Largura": "‎6 centímetros",
      "Altura": "‎7 centímetros",
      "Modelo": "‎205",
      "Número do modelo": "‎205",
      "Dimensões do produto": "‎10 x 6 x 7 cm; 120 g",
      "ASIN": "‎B0798XT2VK",
      "Marca": "‎PW",
      "EAN": "‎6012526986922, 7898100842056",
      "Dimensões do pacote": "21.2 x 13.6 x 3 centímetros",
      "Disponível para compra desde": "24 janeiro 2018",
      "Descontinuado pelo fabricante": "Não"
    },
    "affiliate_url": "https://www.amazon.com.br/Protetor-Contra-Energia-Freezer-Geladeira/dp/B0798XT2VK/ref=zg_bs_g_appliances_d_sccl_14/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:56:47.000Z",
    "spotlight": false
  },
  {
    "asin": "B0BSR4QKZL",
    "title": "SUGGAR LAVADORA DE ROUPAS LAVAMAX ECO 20KG 220V BRANCA LE2002BR",
    "image": "https://m.media-amazon.com/images/I/41rECLQvLwL._AC_SL1200_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 591.26,
    "price_original": 750,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.6,
    "qtd_avaliacoes": 807,
    "coupon_code": null,
    "description": "<ul><li>Lava até 20kg de roupas</li><li>Maior batedor da categoria</li><li>3 molhos e desligamento automatico</li><li>lava edredom de casal tamanho King</li><li>2 dispensers um para sabão e outro para amaciante</li></ul>",
    "informacoes_produto": {
      "Capacidade": "20 quilogramas",
      "Características especiais": "3 níveis de água e filtro cata-fiapos, 6 programas de lavagem, Baixo consumo: 0,12kWh/ciclo, Função reaproveitar água, Timer com programação de 0 a 28 min.",
      "Local do acesso": "Carga superior",
      "Tipo de acabamento": "Pintado branco",
      "Opções de ciclo": "Normal, Heavy Duty",
      "Tipo de controles": "Puxador",
      "Modo de operação": "Totalmente automático",
      "Voltagem": "220 Volts",
      "Número de ciclos padrão": "6",
      "Tipo de instalação": "Independente",
      "Opções de dosador da máquina de lavar": "2 (Detergente e Amaciante)",
      "Dimensões do item P x L x A": "59,5P x 55L x 95,7A centímetros",
      "Peso do item": "13,1 Quilogramas",
      "Material": "Plástico",
      "Material do tambor do aparelho de lavagem de roupa": "Plástico",
      "Nome da marca": "Suggar",
      "Usos recomendados do produto": "Residencial",
      "Nome do modelo": "Lavamax Eco",
      "Componentes incluídos": "manual de instruções",
      "Fabricante": "Suggar",
      "Número do modelo": "LE2002BR",
      "Número da peça": "LE2002BR",
      "Descrição da garantia": "1 ano de garantia",
      "Nome do Tipo de Produto": "Lavadora de roupa",
      "ASIN": "B0BSR4QKZL",
      "Cor": "branca",
      "Dimensões do produto": "59,5P x 55L x 95,7A centímetros",
      "Marca": "Suggar",
      "Local de acesso": "Carga superior"
    },
    "affiliate_url": "https://www.amazon.com.br/SUGGAR-LAVADORA-ROUPAS-LAVAMAX-LE2002BR/dp/B0BSR4QKZL/ref=zg_bs_g_appliances_d_sccl_15/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:56:47.000Z",
    "spotlight": false
  },
  {
    "asin": "B085JFRRSW",
    "title": "MONDIAL Cooktop a Gás, 4 Bocas, Preto/Inox, Bivolt - CTG-01",
    "image": "https://m.media-amazon.com/images/I/517E2Ia2cWL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 349,
    "price_original": 499.9,
    "discount_percentage": 30.0,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 5572,
    "coupon_code": null,
    "description": "<ul><li>DISTRIBUIÇÃO INTELIGENTE DAS BOCAS: Mesa maior, com melhor disposição e aproveitamento entre as bocas. (todas podem ser usadas ao mesmo tempo).</li><li>POTÊNCIA TOTAL DE 8.400W: 1 queimador ultrarrápido (2650W), 1 queimador rápido (2350W) e 2 queimadores semirrápidos (2x 1700W).</li><li>ACENDIMENTO AUTOMÁTICO: Agilidade e segurança para o dia a dia. Basta girar o botão que a chama acende.</li><li>MESA DE VIDRO TEMPERADO: Garante elegância ao ambiente, alta durabilidade e praticidade na limpeza.</li><li>DESIGN MODERNO: Botões com detalhes em aço inox.</li><li>BOTÕES REMOVÍVEIS: Os botões saem com facilidade, evitando o acúmulo de gordura e possibilitando uma limpeza mais eficaz.</li></ul>",
    "informacoes_produto": {
      "Número de elementos de aquecimento": "4",
      "Fonte de energia": "Alimentado a gás",
      "Tipo de combustível": "Gás natural",
      "Características especiais": "Acendimento automático",
      "Elemento de aquecimento": "Gás",
      "Tipo de sistema de ignição": "Eletrônico",
      "Tipo de controle": "Botão de pressão",
      "Tipo de instalação": "Independente",
      "Voltagem": "110,22 Volts",
      "Potência": "8400 watts",
      "Dimensões do item P x L x A": "46P x 60L x 17A centímetros",
      "Peso do item": "7,5 Quilogramas",
      "Tamanho": "4 Bocas",
      "Material da superfície do aquecedor": "Vidro temperado",
      "Material": "Aço inoxidável, Vidro temperado",
      "Nome da marca": "MONDIAL",
      "Componentes incluídos": "Cooktop; Manual de Instruções",
      "Fabricante": "Mondial",
      "Número de identificação de comércio internacional": "07899882310078",
      "Número da peça": "1",
      "Número do modelo": "CTG-01",
      "País de origem": "Brasil",
      "Contagem de unidades": "1.0 Peça",
      "Nome do Tipo de Produto": "CTG-01",
      "Descrição da garantia": "12 Meses",
      "ASIN": "B085JFRRSW",
      "Cor": "Preto/Inox",
      "Marca": "MONDIAL",
      "Elementos de aquecimento": "4",
      "Fonte de alimentação": "Alimentado a gás"
    },
    "affiliate_url": "https://www.amazon.com.br/MONDIAL-Cooktop-Bocas-Preto-Bivolt/dp/B085JFRRSW/ref=zg_bs_g_appliances_d_sccl_16/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:56:47.000Z",
    "spotlight": false
  },
  {
    "asin": "B09B8W3KQP",
    "title": "Máquina de Lavar Electrolux 15kg Branca Essential Care com Cesto Inox e Jet&Clean (LED15) - 127V",
    "image": "https://m.media-amazon.com/images/I/41pS08Q7EoL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 2099,
    "price_original": 4449,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 853,
    "coupon_code": null,
    "description": "<ul><li>ÚNICO³ COM TECNOLOGIA JET&amp;CLEAN: Dispenser autolimpante com tecnologia Jet&amp;Clean, que através de fortes jatos de água otimiza o uso do sabão e do amaciante, além de diluí-los em até 100%¹ antes de entrarem em contato com as roupas, evitando manchas e relavagem. ¹Teste comparativo interno realizado com a LT10B (sem Jet&amp;Clean), verificando a distribuição dos insumos líquidos na carga de roupa mais próxima ao fundo do cesto. Uso de amaciante líquido (150ml) e 8kg de carga, com pressão de água de 240kPa. Área atingida pelo amaciante de 99,99% e desvio padrão 0,01.</li><li>ULTRA FILTER PEGA FIAPOS: Retém e armazena até 8 vezes² mais fiapos: sistema de filtragem que retém os fiapos desagradáveis que podem ficar nas roupas após a lavagem. ²O maior volume interno do filtro pode armazenar até 8 vezes mais fiapos. Este produto possui filtro com volume interno 8 vezes maior quando comparado ao volume interno do filtro do produto LT12F, segundo procedimento interno em laboratório da Electrolux.</li><li>SISTEMA DE LAVAGEM COM CICLOS RÁPIDOS: Vida longa às roupas. Possui um sistema de lavagem, que otimiza o tempo dos programas de forma automática, deixando-os mais rápidos quando necessário e mantendo a mesma performance. Isso promove mais cuidado e menos desgaste das roupas.</li><li>FUNÇÃO LIMPEZA DE CESTO: Possui uma função de autolimpeza no cesto da máquina. Essa limpeza, evita que resíduos de outras lavagens fiquem acumulados no cesto, promovendo uma lavagem mais eficiente.</li><li>FUNÇÃO TURBO AGITAÇÃO/SECAGEM: Aumenta a ação mecânica da agitação melhorando o desempenho da lavagem. Indicado para tirar manchas mais difíceis ou roupas mais sujas. Também aumenta o tempo de centrifugação permitindo que as roupas saiam menos úmidas da lavadora comparado a uma centrifugação normal.</li><li>FUNÇÃO DUPLO ENXÁGUE: Função que promove mais performance no enxágue e menos resíduos de sabão nas roupas.</li><li>FUNÇÃO REUTILIZAÇÃO DE ÁGUA: Função que permite economia de água através do reaproveitamento durante a lavagem, reutilizando-a para outros fins, como por exemplo lavar o chão.</li></ul>",
    "informacoes_produto": {
      "Capacidade": "15 quilogramas",
      "Características especiais": "Dispenser Jet&amp;Clean, Ultra Filter Pega Fiapos, Ciclos Rápidos, Limpeza de Cesto, Turbo Agitação/Secagem, Duplo Enxágue, Reutilização de Água",
      "Local do acesso": "Carga superior",
      "Tipo de acabamento": "Branca",
      "Opções de ciclo": "Ciclos Rápidos, Função Duplo Enxágue",
      "Tipo de controles": "Botão de pressão",
      "Modo de operação": "Totalmente automático",
      "Voltagem": "127 Volts",
      "Número de ciclos padrão": "11",
      "Entrada de interface humana": "Botões",
      "Tipo de instalação": "Independente",
      "Opções de dosador da máquina de lavar": "Dispenser Jet&amp;Clean",
      "Número de programas": "11",
      "Dimensões do item P x L x A": "72,4P x 66,2L x 105,2A centímetros",
      "Peso do item": "48 Quilogramas",
      "Profundidade do item": "72, 4 centimetros",
      "Nome da marca": "Electrolux",
      "Usos recomendados do produto": "Residencial",
      "Nome do modelo": "LED15",
      "Componentes incluídos": "1 máquina de lavar, 1 guia rápido, 1 curva da mangueira",
      "Fabricante": "Electrolux",
      "Número do modelo": "LED15",
      "Número da peça": "LED15",
      "Nome do Tipo de Produto": "Máquina de Lavar",
      "ASIN": "B09B8W3KQP",
      "Material": "Plástico",
      "Material do tambor do aparelho de lavagem de roupa": "Aço inoxidável",
      "Cor": "Branca",
      "Dimensões do produto": "72,4P x 66,2L x 105,2A centímetros",
      "Marca": "Electrolux",
      "Local de acesso": "Carga superior"
    },
    "affiliate_url": "https://www.amazon.com.br/Lavadora-Electrolux-LED15-Essential-Filter/dp/B09B8W3KQP/ref=zg_bs_g_appliances_d_sccl_17/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:56:47.000Z",
    "spotlight": true
  },
  {
    "asin": "B0B7C9HXGL",
    "title": "Cooktop 4 Bocas Itatiaia Essencial com Mesa de Vidro Temperado e Acendimento Automático Preto Bivolt",
    "image": "https://m.media-amazon.com/images/I/71uLqItiKiL._AC_SL1500_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 299.86,
    "price_original": 2899,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 1319,
    "coupon_code": null,
    "description": "<ul><li>COOKTOP ITATIAIA ESS 4Q BIVOLT PTO</li><li>Dimensões do produto: 16,5 X 56,5 X 45</li><li>Marca do produto: Itaiaia.</li><li>Cor do produto: Preto.</li></ul>",
    "informacoes_produto": {
      "Número de elementos de aquecimento": "4",
      "Fonte de energia": "Gás GLP/GN",
      "Tipo de combustível": "Gás natural",
      "Características especiais": "ACENDIMENTO FÁCIL, FACILIDADE NA LIMPEZA, POTÊNCIA E AGILIDADE",
      "Elemento de aquecimento": "Aço inoxidável",
      "Tipo de controle": "Manípulos",
      "Tipo de instalação": "Embutido",
      "Voltagem": "110.22",
      "Potência": "3000 watts",
      "Dimensões do item P x L x A": "45P x 56,5L x 16A centímetros",
      "Peso do item": "6,64 Quilogramas",
      "Tamanho": "16 cm (A) x 56.5 cm (L) x 45 cm (P)",
      "Cor": "Preto",
      "Cor do Acabamento": "Preto",
      "Nome da marca": "Itatiaia",
      "Componentes incluídos": "Cooktop",
      "Fabricante": "Itatiaia",
      "Número do modelo": "3700000192",
      "Nome do Tipo de Produto": "Cooktop",
      "Descrição da garantia": "12 MESES COM O FABRICANTE",
      "ASIN": "B0B7C9HXGL",
      "Material da superfície do aquecedor": "Vidro temperado",
      "Material": "Vidro Temperado 6mm",
      "Marca": "Itatiaia",
      "Elementos de aquecimento": "4",
      "Fonte de alimentação": "Gás GLP/GN"
    },
    "affiliate_url": "https://www.amazon.com.br/Itatiaia-Essencial-Temperado-Acendimento-Autom%C3%A1tico/dp/B0B7C9HXGL/ref=zg_bs_g_appliances_d_sccl_18/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:54:24.000Z",
    "spotlight": true
  },
  {
    "asin": "B0816YJYQB",
    "title": "SUGGAR DEPURADOR DE AR SLIM DE EMBUTIR 60CM INOX 220V DE62IX",
    "image": "https://m.media-amazon.com/images/I/51ciFDrjQLL._AC_SL1200_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 675,
    "price_original": 879,
    "discount_percentage": 23.0,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 979,
    "coupon_code": null,
    "description": "<ul><li>Grande capacidade de sucção: 390m³/h</li><li>Dupla filtragem</li><li>Tela deslizante</li><li>Dupla função: coifa e depurador</li><li>Baixo consumo: 0,12kWh</li></ul>",
    "informacoes_produto": {
      "Características especiais": "Telas em alumínio lavável, eliminam gordura e fumaça, filtro de carvão ativado, elimina odores indesejados",
      "Capacidade do fluxo de ar": "390 Metros cúbicos por hora",
      "Nível de ruído": "65 Decibéis",
      "Tipo de montagem": "Montagem na parede",
      "Tipo de controles": "Toque",
      "Voltagem": "220 Volts",
      "Número de velocidades": "2",
      "Tipo de filtro": "HEPA",
      "Tipo de ventilação": "Ducted/Vented",
      "Cor": "inox",
      "Tipo de acabamento": "Aço inoxidável",
      "Formato do item": "Embutido",
      "Design da Coifa": "Coifa sob Armário de Fogão",
      "Material": "Aço inoxidável",
      "Nome da marca": "Suggar",
      "Componentes incluídos": "Manual de instruções",
      "Número do modelo": "DE62IX",
      "Fabricante": "Suggar",
      "Número da peça": "DE62IX",
      "Nome do Tipo de Produto": "depurador de ar",
      "Descrição da garantia": "1 ano com o fabricante",
      "ASIN": "B0816YJYQB",
      "Dimensões do item P x L x A": "16P x 16L x 40A centímetros",
      "Peso do item": "6 Quilogramas",
      "Marca": "Suggar",
      "Dimensões do produto": "16P x 16L x 40A centímetros"
    },
    "affiliate_url": "https://www.amazon.com.br/SUGGAR-DEPURADOR-SLIM-EMBUTIR-DE62IX/dp/B0816YJYQB/ref=zg_bs_g_appliances_d_sccl_19/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:56:47.000Z",
    "spotlight": false
  },
  {
    "asin": "B07GWXBGYS",
    "title": "FISCHER COOKTOP GÁS 5 BOCAS TC INFINITY MESA INOX BIVOLT 23678-54121",
    "image": "https://m.media-amazon.com/images/I/71OM7XG9BbL._AC_SL1500_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 979.9,
    "price_original": 1199,
    "discount_percentage": 18.0,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.5,
    "qtd_avaliacoes": 2016,
    "coupon_code": null,
    "description": "<ul><li>Mesa em aço inox escovado</li><li>1 tripla Chama (3700W), 2 rápido (2900W) e 2 semi-rápido (1750W)</li><li>Queimadores italianos</li><li>Acendimento super automático</li><li>Trempes dupla e individual em ferro fundido com acabamento fosco.</li></ul>",
    "informacoes_produto": {
      "Número de elementos de aquecimento": "5",
      "Fonte de energia": "Alimentado a gás",
      "Tipo de combustível": "Gás GLP / GN",
      "Características especiais": "Manual",
      "Elemento de aquecimento": "Ferro fundido",
      "Tipo de sistema de ignição": "Eletrônico",
      "Tipo de controle": "Botão de pressão",
      "Tipo de instalação": "Embutido",
      "Voltagem": "110 Volts, 220 Volts",
      "Potência": "2900 watts",
      "Compatibilidade com Casa Inteligente": "Não Compatível com Casa Inteligente",
      "Dimensões do item P x L x A": "17,5P x 30,5L x 17,5A centímetros",
      "Peso do item": "9,9 Quilogramas",
      "Tamanho": "Grande",
      "Cor": "INOX",
      "Cor do Acabamento": "Prata",
      "Nome da marca": "Fischer",
      "Componentes incluídos": "01 Etiqueta atenção gás; 01 Etiqueta Inmetro, 01 Manual de instruções, 04 Tiras de espuma para vedação, Cooktop, Trempes individuais; Trempe dupla; Conjunto dos queimadores",
      "Fabricante": "Fischer",
      "Número da peça": "23678-54121",
      "Número do modelo": "23678-54121",
      "País de origem": "Brasil",
      "Contagem de unidades": "1 Unidade",
      "Nome do Tipo de Produto": "Cooktop",
      "Descrição da garantia": "1 ano, sendo: 03 (três) primeiros meses de garantia legal; 09 (nove) últimos meses de garantia contratual / especial",
      "ASIN": "B07GWXBGYS",
      "Material da superfície do aquecedor": "Aço inoxidável",
      "Material": "Aço inoxidável",
      "Marca": "Fischer",
      "Elementos de aquecimento": "5",
      "Fonte de alimentação": "Alimentado a gás"
    },
    "affiliate_url": "https://www.amazon.com.br/Fog%C3%A3o-Cooktop-Fischer-INFINITY-BIVOLT/dp/B07GWXBGYS/ref=zg_bs_g_appliances_d_sccl_20/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:56:47.000Z",
    "spotlight": false
  },
  {
    "asin": "B0B61WJRY5",
    "title": "Samsung Lava e Seca WD11M com Digital Inverter WD11M4473PX Inox Look 11/7kg - 220V",
    "image": "https://m.media-amazon.com/images/I/41F+xukODBL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 3599,
    "price_original": 4449,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 513,
    "coupon_code": null,
    "description": "<ul><li>Inverter</li><li>Cuidado com lã</li></ul>",
    "informacoes_produto": {
      "Capacidade": "11 quilogramas",
      "Características especiais": "Cuidado com lã, Inverter",
      "Opções de ciclo": "Delicados, Lavagem rápida, Lã, Secagem automática",
      "Voltagem": "220 Volts",
      "Local do acesso": "Carregamento frontal",
      "Número de Ciclos de Secagem": "2",
      "Número de ciclos de lavagem": "4",
      "Tipo de acabamento": "Inox Look",
      "Modo de operação": "automático",
      "Cor": "Inox Look",
      "Material do tambor do aparelho de lavagem de roupa": "Aço inox",
      "Nome da marca": "Samsung",
      "Número do modelo": "SAMSUNG",
      "ASIN": "B0B61WJRY5",
      "Dimensões do item P x L x A": "65P x 60L x 85A centímetros",
      "Peso do item": "70 Quilogramas",
      "Marca": "Samsung",
      "Dimensões do produto": "65P x 60L x 85A centímetros"
    },
    "affiliate_url": "https://www.amazon.com.br/Lava-Seca-Samsung-Programas-Lavagem/dp/B0B61WJRY5/ref=zg_bs_g_appliances_d_sccl_21/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:56:47.000Z",
    "spotlight": false
  },
  {
    "asin": "B0G3Y8Y619",
    "title": "Máquina de Lavar Brastemp 14kg com Smart Sensor, Função Reduzir Tempo Branca BWJ14AB",
    "image": "https://m.media-amazon.com/images/I/612AvD2ZDrL._AC_SL1500_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 1839.22,
    "price_original": 4449,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 5.0,
    "qtd_avaliacoes": 6,
    "coupon_code": null,
    "description": "<ul><li>A Lavadora Brastemp 14kg com Smart Sensor economiza até 25% de água e reduz 45 minutos por ciclo. Potência e cuidado em cada lavagem. Compre agora!</li></ul>",
    "informacoes_produto": {
      "Capacidade": "14 quilogramas",
      "Características especiais": "Conectividade inteligente, Lavagem rápida",
      "Local do acesso": "Carga superior",
      "Tipo de acabamento": "Branco",
      "Tipo de controles": "Toque",
      "Modo de operação": "Totalmente automático",
      "Voltagem": "220 Volts",
      "Tipo de instalação": "Independente",
      "Opções de dosador da máquina de lavar": "Dispensador combinado (detergente e aditivos)",
      "Dimensões do item P x L x A": "69,5P x 62,5L x 104A centímetros",
      "Peso do item": "38 Quilogramas",
      "Profundidade do item": "69.5 centimeters",
      "Material do tambor do aparelho de lavagem de roupa": "Aço inoxidável",
      "Nome da marca": "Brastemp",
      "Usos recomendados do produto": "Residencial",
      "Nome do modelo": "BWJ14AB",
      "Componentes incluídos": "Mangueira de drenagem",
      "Fabricante": "BRASTEMP",
      "Número do modelo": "BWJ14AB",
      "Número da peça": "BWJ14AB",
      "Descrição da garantia": "12 meses com o fabricante",
      "ASIN": "B0G3Y8Y619",
      "Cor": "Branco",
      "Dimensões do produto": "69,5P x 62,5L x 104A centímetros",
      "Marca": "Brastemp",
      "Local de acesso": "Carga superior"
    },
    "affiliate_url": "https://www.amazon.com.br/M%C3%A1quina-Branca-Brastemp-Sensor-Lavagem/dp/B0G3Y8Y619/ref=zg_bs_g_appliances_d_sccl_22/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:56:47.000Z",
    "spotlight": true
  },
  {
    "asin": "B0BTZBQDMC",
    "title": "Suporte C/Rodinhas Base Ajustável Máquina Lavar Fogão Geladeira Móveis Resistente Reforçado",
    "image": "https://m.media-amazon.com/images/I/41ARppGGJyL._AC_SL1200_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 30.48,
    "price_original": 37,
    "discount_percentage": 17.0,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.3,
    "qtd_avaliacoes": 2811,
    "coupon_code": null,
    "description": "<ul><li>✅ Movimentar Móveis, Geladeira, Máquina de Lavar e Outros</li><li>✅ Sistema de Freio</li><li>✅ Ajuste de Comprimento</li><li>✅ Base Antiderrapante e Fácil instalação</li><li>✅ Produto Super Resistente Até 200Kg</li></ul>",
    "informacoes_produto": {
      "Nome da marca": "‎Embralumi",
      "Certificação": "‎Não Aplicavel",
      "Dimensões do produto": "‎45 x 5 x 4 cm; 1,35 quilogramas",
      "Tipo de instalação": "‎Travamento das Rodas",
      "Número da Peça": "‎DS11861",
      "Características especiais": "‎Instalação fácil",
      "Cor": "‎Cinza",
      "Tipo de material": "‎Metal",
      "Componentes incluídos": "‎2x Suportes com Rodinhas",
      "Baterias inclusas?": "‎Não",
      "Funciona a bateria ou pilha?": "‎Não",
      "Peso": "‎1350 Gramas",
      "Fabricante": "‎DS",
      "Referência do fabricante": "‎DS11861",
      "ASIN": "‎B0BTZBQDMC",
      "Disponível para compra desde": "3 outubro 2022"
    },
    "affiliate_url": "https://www.amazon.com.br/Rodinhas-Ajust%C3%A1vel-Geladeira-Resistente-Refor%C3%A7ado/dp/B0BTZBQDMC/ref=zg_bs_g_appliances_d_sccl_23/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:56:47.000Z",
    "spotlight": false
  },
  {
    "asin": "B0FJJ3YY9B",
    "title": "Frigobar 93 Litros Inverter Bivolt Branco, Midea",
    "image": "https://m.media-amazon.com/images/I/31FoIRrnzXL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 898.89,
    "price_original": 1299,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.2,
    "qtd_avaliacoes": 283,
    "coupon_code": null,
    "description": "<ul><li>Flexi Volt - Funciona tanto em 127V quanto em 220V, garantindo segurança e liberdade para usar em qualquer tomada.</li><li>Tecnologia Inverter - Proporciona resfriamento rápido e garante a estabilidade da temperatura, preservando os alimentos por mais tempo, com maior economia de energia e oferece baixo nível de ruído.</li><li>Design Compacto - No tamanho ideal para qualquer ambiente, é espaçoso e funcional. Seus 93L acomodam facilmente bebidas, alimentos e até garrafas de 2 litros.</li><li>Compartimento Extrafio - Controle de temperatura, ajuste fácil que garante a temperatura ideal. Bebidas geladas mais rápido, com praticidade e conveniência, sempre que você precisar.</li><li>Prateleiras de Vidro - Design elegante e resistente, Gaveta Organizadora - Perfeita para armazenar frutas e alimentos, Compartimento para 8 Latas - Organização e otimização do espaço interno.</li></ul>",
    "informacoes_produto": {
      "Configuração": "Flexi Volt, Controle de Temperatura, Compartimento Extrafio, Sistema de Refrigeração por Compressor, Frigobar",
      "Características especiais": "* Espaçoso, * Compartimento Extra Frio, * Baixo nível de ruído, * Sistema de Refrigeração por Compressor, * Flexi Volt, * Prateleiras de Vidro, * Controle de Temperatura, * Tecnologia Inverter, * Maior Economia de Energia, * Design Compacto, * Compartimento de Latas",
      "Número de portas": "1",
      "Tipo de sistema de degelo": "Manual",
      "Voltagem": "110 Volts, 220 Volts",
      "Fator de forma": "Compacto",
      "Método de resfriamento": "Compressor",
      "Número de prateleiras": "3",
      "Controle de temperatura ajustável": "Sim",
      "Orientação de abertura da porta": "Direita",
      "Tem Congelador Conversível": "Não",
      "É alimentado por energia elétrica?": "Sim",
      "Fonte de energia": "Elétrico com fio",
      "Cor": "branco",
      "É Estilo Retrô": "Não",
      "Dimensões do item P x L x A": "45P x 47,2L x 86A centímetros",
      "Capacidade": "93 litros",
      "Peso do item": "18 Quilogramas",
      "Consumo de energia anual": "90 Kilowatt Hours Per Year",
      "Capacidade Líquida do Refrigerador": "93 Litros",
      "Tamanho": "93L",
      "Capacidade de comida fresca": "93 Litros",
      "Tipo de instalação": "Independente",
      "Avaliação por estrelas do BEE": "5 Estrelas",
      "Nome da marca": "Midea",
      "Número do modelo": "MDRD142FGD013",
      "Número da peça": "MDRD142FGD013",
      "Componentes incluídos": "Frigobar e manual de usuário",
      "Fabricante": "Midea",
      "Descrição da garantia": "12 meses no produto - 10 anos no compressor",
      "País de origem": "China",
      "Nome do Tipo de Produto": "Frigobar, 93L, branco, bivolt, Midea",
      "ASIN": "B0FJJ3YY9B",
      "Dimensões do produto": "45P x 47,2L x 86A centímetros",
      "Marca": "Midea"
    },
    "affiliate_url": "https://www.amazon.com.br/Frigobar-Litros-Inverter-Bivolt-Midea/dp/B0FJJ3YY9B/ref=zg_bs_g_appliances_d_sccl_24/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:56:47.000Z",
    "spotlight": false
  },
  {
    "asin": "B0B3SHRP7S",
    "title": "SUGGAR DEPURADOR COIFA DE AR SLIM 80CM INOX 110V DPS181IX",
    "image": "https://m.media-amazon.com/images/I/41NHJDKA3XL._AC_SL1200_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 509,
    "price_original": 559,
    "discount_percentage": 8.0,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.5,
    "qtd_avaliacoes": 1324,
    "coupon_code": null,
    "description": "<ul><li>Grande capacidade de sucção: 390m³/h</li><li>Dupla filtragem</li><li>3 velocidades</li><li>potencia 105W</li><li>Baixo consumo: 0,12kWh</li></ul>",
    "informacoes_produto": {
      "Características especiais": "Dupla filtragem",
      "Capacidade do fluxo de ar": "390 Metros cúbicos por hora",
      "Nível de ruído": "65 Decibéis",
      "Tipo de montagem": "Montagem na parede",
      "Tipo de controles": "Botão de pressão",
      "Voltagem": "110 Volts",
      "Número de velocidades": "3",
      "Tipo de filtro": "tela de alumínio lavável e filtro de carvão ativado",
      "Tipo de ventilação": "Ductless/Recirculating",
      "Cor": "Inox",
      "Tipo de acabamento": "Aço inoxidável",
      "Formato do item": "Montagem na parede",
      "Design da Coifa": "Coifa de Exaustor Montado na Parede",
      "Material": "Aço inoxidável",
      "Nome da marca": "Suggar",
      "Componentes incluídos": "Manual de instruções",
      "Número do modelo": "DPS181IX",
      "Fabricante": "Suggar",
      "Número da peça": "DPS181IX",
      "País de origem": "Brasil",
      "Nome do Tipo de Produto": "depurador de ar",
      "Descrição da garantia": "1 ano de garantia",
      "ASIN": "B0B3SHRP7S",
      "Dimensões do item P x L x A": "48P x 80L x 8,5A centímetros",
      "Peso do item": "5,1 Quilogramas",
      "Marca": "Suggar",
      "Dimensões do produto": "48P x 80L x 8,5A centímetros"
    },
    "affiliate_url": "https://www.amazon.com.br/SUGGAR-DEPURADOR-SLIM-80CM-DPS181IX/dp/B0B3SHRP7S/ref=zg_bs_g_appliances_d_sccl_25/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:56:47.000Z",
    "spotlight": false
  },
  {
    "asin": "B07Q6LVF9J",
    "title": "Secadora de Roupa Mueller Solaris 8Kg 220V",
    "image": "https://m.media-amazon.com/images/I/513006cv6ZL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 484.4,
    "price_original": 549.9,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.9,
    "qtd_avaliacoes": 284,
    "coupon_code": null,
    "description": "<ul><li>Seca Até 8 Kg</li><li>5 Varões e 6 Cabides Removíveis : Praticidade em Acomodar todos os Tipos de Roupas</li><li>Seletor de Ar Quente ou Frio : Escolha o Melhor Tipo de Secagem para Suas Roupas</li><li>Novo Timer 120 Minutos , Roupas Secas em Menos Tempo com Função Amaciante</li><li>Maior Camera de Secagem : Destaque do Mercado por ter 90 cm de altura</li></ul>",
    "informacoes_produto": {
      "Nome da marca": "Mueller",
      "Nome do modelo": "Secadora de Roupa Soleil 8 Kg - 220 V",
      "Fabricante": "Mueller",
      "Número do modelo": "600008054",
      "Número da peça": "600008054",
      "Descrição da garantia": "1 ano com o fabricante",
      "Componentes incluídos": "6 Cabides",
      "Nome do Tipo de Produto": "Secadoras de Roupas",
      "ASIN": "B07Q6LVF9J",
      "Fator de forma": "Carga frontal",
      "Local do acesso": "Carga frontal",
      "Capacidade": "8 quilogramas",
      "Peso do item": "6,6 Quilogramas",
      "Cor": "Branco",
      "Material": "Plástico",
      "Marca": "Mueller",
      "Local de acesso": "Carga frontal"
    },
    "affiliate_url": "https://www.amazon.com.br/Secadora-Roupa-Mueller-Solaris-220V/dp/B07Q6LVF9J/ref=zg_bs_g_appliances_d_sccl_26/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:56:47.000Z",
    "spotlight": false
  },
  {
    "asin": "B0FK163DY6",
    "title": "Freezer Horizontal 100L Inverter Bivolt Branco Midea",
    "image": "https://m.media-amazon.com/images/I/41GOo1UPNmL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 1221.06,
    "price_original": 1579,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.6,
    "qtd_avaliacoes": 59,
    "coupon_code": null,
    "description": "<ul><li>O Freezer Horizontal Midea 100L é perfeito para quem quer preservar alimentos resfriados, conservados ou congelados de forma rápida.</li><li>Inverter: Baixo nível de ruido, resfriamento rápido e super econômico. - Flexbeer: Perfeito para gelar cervejas, ajuste na temperatura exata, com capacidade para 160 latinhas.</li><li>Tripla função: Pode ser usado com freezer, refrigerador e conservador. Opera entre 0°C e -28°C</li><li>Compacto por fora e Espaçoso por dentro: Perfeito para residências</li><li>Novo cesto de armazenagem: Agora com novo design para melhor organização dos alimentos. - Flexi-volt: Funciona tanto em 127V quanto em 220V.</li></ul>",
    "informacoes_produto": {
      "Nome da marca": "Midea",
      "Fabricante": "Midea",
      "Componentes incluídos": "Freezer Horizontal, cesto de armazenagem e manual do usuário",
      "Nome do Tipo de Produto": "Freezer Horizontal 100 litros",
      "Número do modelo": "MDRC151FZD013",
      "Número da peça": "MDRC151FZD013",
      "Descrição da garantia": "12 meses e 10 anos no compresso",
      "ASIN": "B0FK163DY6",
      "Potência": "100 watts",
      "Orientação de abertura da porta": "Direita",
      "Voltagem": "110 Volts, 220 Volts",
      "Capacidade": "100 litros",
      "Tipo de instalação": "Sobre bancada",
      "Cor": "Branco",
      "Tipo de material da porta": "Plástico",
      "Dimensões do item P x L x A": "49,5P x 54,5L x 85A centímetros",
      "Peso do item": "19,5 Quilogramas",
      "Dimensões do produto": "49,5P x 54,5L x 85A centímetros",
      "Marca": "Midea",
      "Peso do produto": "19,5 Quilogramas"
    },
    "affiliate_url": "https://www.amazon.com.br/Freezer-Horizontal-Inverter-Bivolt-Midea/dp/B0FK163DY6/ref=zg_bs_g_appliances_d_sccl_27/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:56:47.000Z",
    "spotlight": false
  },
  {
    "asin": "B0GQC5GM8M",
    "title": "Frigobar Eos 71 Litros Ice Compact Branco Efb80 220v",
    "image": "https://m.media-amazon.com/images/I/41W+miLnA1L._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 697.54,
    "price_original": 865.56,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 5.0,
    "qtd_avaliacoes": 2,
    "coupon_code": null,
    "description": "<ul><li>Classificação Energética/Inmetro A</li><li>Garantia do Compressor 10 anos</li><li>Degelo Manual</li></ul>",
    "informacoes_produto": {
      "Configuração": "Congelador interno compacto",
      "Características especiais": "Leve",
      "Número de portas": "1",
      "Tipo de sistema de degelo": "Manual",
      "Voltagem": "220 Volts",
      "Fator de forma": "Compacto",
      "Método de resfriamento": "Compressor",
      "Número de prateleiras": "2",
      "Controle de temperatura ajustável": "Sim",
      "Orientação de abertura da porta": "Direita",
      "É alimentado por energia elétrica?": "Sim",
      "Total de Prateleiras de Porta": "1",
      "Fonte de energia": "Elétrico com fio",
      "Cor": "branco",
      "Dimensões do item P x L x A": "47P x 44,9L x 67,6A centímetros",
      "Capacidade": "76 litros",
      "Capacidade do freezer": "10 Litros",
      "Peso do item": "18,5 Quilogramas",
      "Consumo de energia anual": "1 Kilowatt Hours Per Year",
      "Capacidade Líquida do Refrigerador": "71 Litros",
      "Tamanho": "71 litros",
      "Capacidade de comida fresca": "71 Litros",
      "Tipo de instalação": "Independente",
      "Tipo de material da porta": "Alumínio",
      "Nome da marca": "EOS",
      "Nome do modelo": "EFB80 220V",
      "Número do modelo": "EFB80 220V",
      "Número da peça": "EFB80",
      "Componentes incluídos": "Manual",
      "Fabricante": "EOS",
      "Descrição da garantia": "12 meses",
      "País de origem": "Brasil",
      "ASIN": "B0GQC5GM8M",
      "Dimensões do produto": "47P x 44,9L x 67,6A centímetros",
      "Marca": "EOS"
    },
    "affiliate_url": "https://www.amazon.com.br/Frigobar-Litros-Compact-Branco-Efb80/dp/B0GQC5GM8M/ref=zg_bs_g_appliances_d_sccl_28/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:56:47.000Z",
    "spotlight": false
  },
  {
    "asin": "B0GWFNV422",
    "title": "Máquina de Lavar CWN14AB 14 kg com Modo Eco Consul",
    "image": "https://m.media-amazon.com/images/I/51YcKfJeoGL._AC_SL1500_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 1719,
    "price_original": 4449,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 10,
    "coupon_code": null,
    "description": "<ul><li>Conheça a Máquina de Lavar Consul 14kg feita para durar. Economia real com Modo Eco e roupas menos tempo no varal. Robustez testada em mais de 3.000 ciclos.</li></ul>",
    "informacoes_produto": {
      "Capacidade": "14 quilogramas",
      "Características especiais": "Alta eficiência",
      "Local do acesso": "Superior",
      "Tipo de acabamento": "Acabamento Liso",
      "Opções de ciclo": "Delicadas, Dia A Dia, Esportivas, Jeans E Casacos, Tênis",
      "Tipo de controles": "Digital Com Botões E Seletor Rotativo",
      "Modo de operação": "Totalmente automático",
      "Voltagem": "110 Volts",
      "Número de ciclos padrão": "12",
      "Entrada de interface humana": "Botões, Seletor",
      "Tipo de instalação": "Independente",
      "Opções de dosador da máquina de lavar": "Dispenser Para Alvejante, Dispenser Para Amaciante, Dispenser Para Sabão Em Pó",
      "Dimensões do item P x L x A": "65P x 58L x 97A centímetros",
      "Peso do item": "32 Quilogramas",
      "Profundidade do item": "65.0 Centimeters",
      "Cor": "Branco",
      "Nome da marca": "Consul",
      "Usos recomendados do produto": "Edredons, Jeans E Casacos, Panos De Limpeza, Redes, Roupas Brancas, Roupas De Cama E Banho, Roupas Delicadas, Roupas Do Dia A Dia, Roupas Esportivas, Tênis",
      "Nome do modelo": "CWN14ABANA",
      "Componentes incluídos": "Cabo de alimentação",
      "Fabricante": "Consul",
      "Número do modelo": "326199114",
      "Número da peça": "326199114",
      "Descrição da garantia": "12",
      "ASIN": "B0GWFNV422",
      "Material": "Plástico, aço inoxidável",
      "Material do tambor do aparelho de lavagem de roupa": "Aço Inoxidável",
      "Dimensões do produto": "65P x 58L x 97A centímetros",
      "Marca": "Consul",
      "Local de acesso": "Superior"
    },
    "affiliate_url": "https://www.amazon.com.br/M%C3%A1quina-Lavar-CWN14AB-Modo-Consul/dp/B0GWFNV422/ref=zg_bs_g_appliances_d_sccl_29/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:56:47.000Z",
    "spotlight": true
  },
  {
    "asin": "B0GJG36MCZ",
    "title": "Frigobar 45 Litros Inverter Bivolt Branco",
    "image": "https://m.media-amazon.com/images/I/31d6VuVOqQL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 628.99,
    "price_original": 899,
    "discount_percentage": null,
    "tem_selo_prime": false,
    "tem_oferta": true,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 23,
    "coupon_code": null,
    "description": "<ul><li>Tecnologia Inverter - Resfriamento rápido, garante a estabilidade da temperatura, preservando os alimentos por mais tempo, contribui para uma maior economia de energia com baixo nível de ruído.</li><li>Flexi Volt - Funciona tanto em 127V quanto em 220V, garantindo segurança e liberdade para usar em qualquer tomada.</li><li>Design Compacto - No tamanho ideal para qualquer ambiente, é espaçoso e funcional. Seus 45L acomodam facilmente bebidas, alimentos e até garrafas de 2 litros.</li><li>Compartimento Extra frio - Bebidas geladas mais rápido, com praticidade e conveniência, sempre que você precisar.</li><li>Compartimento de Latas - Mais organização e otimização do espaço interno com o compartimento para latas.</li></ul>",
    "informacoes_produto": {
      "Características especiais": "Compressor inversor",
      "Número de portas": "1",
      "Tipo de sistema de degelo": "Manual",
      "Voltagem": "110 Volts, 220 Volts",
      "Fator de forma": "Compacto",
      "Método de resfriamento": "Compressor",
      "Número de prateleiras": "1",
      "Orientação de abertura da porta": "Direita",
      "É alimentado por energia elétrica?": "Sim",
      "Compatibilidade com Casa Inteligente": "Não Compatível com Casa Inteligente",
      "Fonte de energia": "Elétrico com fio",
      "Cor": "branco",
      "Dimensões do item P x L x A": "45,5P x 47,2L x 49,2A centímetros",
      "Capacidade": "45 litros",
      "Capacidade do freezer": "45 Litros",
      "Peso do item": "13 Quilogramas",
      "Consumo de energia anual": "79,2 Kilowatt Hours Per Year",
      "Capacidade Líquida do Refrigerador": "45 Litros",
      "Tamanho": "45 Litros",
      "Capacidade de comida fresca": "45 Litros",
      "Nome da marca": "Midea",
      "Número do modelo": "MDRD086FGD013",
      "Número da peça": "MDRD086FGD013",
      "Componentes incluídos": "Frigobar e manual",
      "Fabricante": "Midea",
      "Descrição da garantia": "12 meses no produto - 10 anos no compressor",
      "País de origem": "China",
      "Nome do Tipo de Produto": "Frigobar",
      "Contagem de unidades": "1 Count",
      "ASIN": "B0GJG36MCZ",
      "Dimensões do produto": "45,5P x 47,2L x 49,2A centímetros",
      "Marca": "Midea"
    },
    "affiliate_url": "https://www.amazon.com.br/Frigobar-Litros-Inverter-Bivolt-Branco/dp/B0GJG36MCZ/ref=zg_bs_g_appliances_d_sccl_30/146-4713483-2937012?tag=mixdm22-20",
    "last_checked_at": "2026-07-19T20:56:47.000Z",
    "spotlight": false
  }
];
