const PRODUCTS = [
  {
    "asin": "B0H4J13B2M",
    "title": "Notebook Gamer Lenovo Loq, I5-12450hx, 16gb Ddr5, 1tb Ssd, Rtx 4050 6gb, 15.6\" Fhd, W11, Cinza - 83me0001br",
    "image": "https://m.media-amazon.com/images/I/51lylzSiLML._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 6099.99,
    "price_original": 6665.56,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 5.0,
    "qtd_avaliacoes": 1,
    "coupon_code": null,
    "description": "<ul><li>Notebook Gamer Lenovo LOQ Intel i5 16GB RAM 1TB SSD RTX 4050</li><li>Placa de vídeo dedicada RTX 4050 6GB</li><li>Processador Intel Core i5-12450HX</li></ul>",
    "informacoes_produto": {
      "Marca": "Lenovo",
      "Nome do modelo": "LOQ",
      "Tamanho da tela": "15,6 Polegadas",
      "Tamanho do disco rígido": "1 TB",
      "Modelo da CPU": "Intel Core i5",
      "Tamanho instalado da memória RAM": "16 GB",
      "Sistema operacional": "Windows 11",
      "Descrição da placa de vídeo": "Dedicada",
      "Velocidade da CPU": "31 GHz",
      "Descrição do disco rígido": "SSD"
    },
    "affiliate_url": "https://www.amazon.com.br/Notebook-Gamer-Lenovo-I5-12450hx-Cinza/dp/B0H4J13B2M?ref=dlx_deals_dg_dcl_B0H4J13B2M_dt_sl14_88_pi&pf_rd_r=W4XS7QFQ54H10VPE6BKR&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": true
  },
  {
    "asin": "B0918FHY6P",
    "title": "L'Oréal Professionnel Óleo 10 em 1 Absolut Repair | Multi-benefícios para cabelos secos e danificados | Repara e Promove Brilho | Com Gold Quinoa e Proteínas",
    "image": "https://m.media-amazon.com/images/I/61wfwHNv-NL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 123.39,
    "price_original": 247.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 22703,
    "coupon_code": null,
    "description": "<ul><li>Óleo de tratamento leave-in multibenefícios 10 em 1, que oferece nutrição, reparação instantânea e brilho para os fios</li><li>Sua fórmula profissional é enriquecida com Proteína do Trigo, garantindo uma restauração profunda e cabelos mais resistentes</li><li>Proporciona maciez e maleabilidade com um toque leve, sem pesar, facilitando o cuidado diário</li><li>Oferece proteção térmica e contra agressões externas, mantendo os cabelos saudáveis e protegidos no dia a dia</li><li>Repara a fibra capilar danificada, devolvendo a suavidade e o brilho para um resultado de salão instantâneo em casa</li></ul>",
    "informacoes_produto": {
      "Tipo de cabelo": "Fino",
      "Tipo de material livre": "Sem conservantes",
      "Aroma": "Sem perfume",
      "Volume líquido": "1 Onças líquidas"
    },
    "affiliate_url": "https://www.amazon.com.br/LOr%C3%A9al-Professionnel-Multi-benef%C3%ADcios-danificados-Prote%C3%ADnas/dp/B0918FHY6P?ref=dlx_deals_dg_dcl_B0918FHY6P_dt_sl14_88_pi&pf_rd_r=W4XS7QFQ54H10VPE6BKR&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B0H4HYLQ71",
    "title": "Notebook Gamer Lenovo Loq 15irx9, 15.6\" Full Hd 144hz, Intel Core I5-13450hx, 16gb, 512gb Ssd, Nvidia Rtx 4050, Linux - 83khs00300",
    "image": "https://m.media-amazon.com/images/I/61+CippnCvL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 5899.0,
    "price_original": 6555.54,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": null,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Notebook-Lenovo-15irx9-I5-13450hx-Nvidia/dp/B0H4HYLQ71?ref=dlx_deals_dg_dcl_B0H4HYLQ71_dt_sl14_88_pi&pf_rd_r=2MVQMGMQZXHE0GEQ6KKX&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": true
  },
  {
    "asin": "B0GT6LW2VN",
    "title": "JBL, Caixa de Som, PartyBox Encore Essential 2 Mic, Show de Luzes, Bluetooth, Portátil, Resistente a Respingos, Bateria de até 15h, Som JBL Pro Sound, AI Sound Boost, 100 W RMS",
    "image": "https://m.media-amazon.com/images/I/61Z9gLQHMIL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 1939.0,
    "price_original": 2699.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": null,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/JBL-Essential-Bluetooth-Resistente-Respingos/dp/B0GT6LW2VN?ref=dlx_deals_dg_dcl_B0GT6LW2VN_dt_sl14_88_pi&pf_rd_r=2MVQMGMQZXHE0GEQ6KKX&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": true
  },
  {
    "asin": "B07VRYJWPB",
    "title": "Finish Power Powder Advanced Detergente para Lava Louças em Pó 2,5kg",
    "image": "https://m.media-amazon.com/images/I/61FuIlOh2GL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 98.78,
    "price_original": 146.59,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 22494,
    "coupon_code": null,
    "description": "<ul><li>Finish Power Powder Advanced é o seu detergente lava louças em pó que oferece limpeza profunda na dose certa. Recomendado pelos principais fabricantes de lava louças do Brasil e do mundo.</li><li>Sua louça do dia a dia vai ficar limpa de primeira, sem necessidade de pré-enxague. Possui ingredientes na fórmula que promovem o cuidado e proteção das louças.</li><li>Exclusiva fórmula com oxigênio ativo e enzimas que promovem limpeza através de sua ação desengordurante e da remoção de sujeiras.</li><li>Vem com medidor que ajuda a dosar corretamente a quantidade do detergente lava louças.</li><li>Usar lava louças remove até as sujeiras mais difíceis, sem bagunça, sem ressecar as mãos. É mais qualidade de vida!</li></ul>",
    "informacoes_produto": {
      "Marca": "Finish",
      "Forma do produto": "Pó",
      "Aroma": "Sem perfume",
      "Característica do material": "Sem perfume",
      "Número de itens": "4"
    },
    "affiliate_url": "https://www.amazon.com.br/Detergente-Para-Lou%C3%A7as-Finish-Advanced/dp/B07VRYJWPB?ref=dlx_deals_dg_dcl_B07VRYJWPB_dt_sl14_88_pi&pf_rd_r=2MVQMGMQZXHE0GEQ6KKX&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=9ZOMT9Jm0JH%2Ft%2BWi68iDSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B0DYVNRG3B",
    "title": "Celular Samsung Galaxy A36 5G 128GB, 6GB RAM, Câmera 50MP, IP67, Super AMOLED 6.7\", Recursos AI, Branco",
    "image": "https://m.media-amazon.com/images/I/613Vrz+GcaL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 1449.0,
    "price_original": 2699.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 2479,
    "coupon_code": null,
    "description": "<ul><li>Feito para Durar: até 6 atualizações de Android e Segurança</li><li>Tela imersiva de 6.7\" Super AMOLED com Vision Booster</li><li>Resistente à água e poeira com IP67</li><li>Câmera com recursos de AI e Nightography / Circule para Pesquisar no Google</li><li>Bateria de 5000 mAh e carregamento rápido de até 45W</li></ul>",
    "informacoes_produto": {
      "Marca": "Samsung",
      "Sistema operacional": "Android 15.0",
      "Tamanho instalado da memória RAM": "6 GB",
      "Modelo da CPU": "A-Series",
      "Velocidade da CPU": "2 GHz"
    },
    "affiliate_url": "https://www.amazon.com.br/Celular-Samsung-Galaxy-C%C3%A2mera-Recursos/dp/B0DYVNRG3B?ref=dlx_deals_dg_dcl_B0DYVNRG3B_dt_sl14_88_pi&pf_rd_r=W4XS7QFQ54H10VPE6BKR&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": true
  },
  {
    "asin": "B0B61WJRY5",
    "title": "Samsung Lava e Seca WD11M com Digital Inverter WD11M4473PX Inox Look 11/7kg - 220V",
    "image": "https://m.media-amazon.com/images/I/41F+xukODBL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 3599.0,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": null,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Lava-Seca-Samsung-Programas-Lavagem/dp/B0B61WJRY5?ref=dlx_deals_dg_dcl_B0B61WJRY5_dt_sl14_88_pi&pf_rd_r=2MVQMGMQZXHE0GEQ6KKX&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B00HGNXC8Q",
    "title": "Máquina de Lavar Panasonic 15kg Branca Função Vanish NA-F150B1W 127v",
    "image": "https://m.media-amazon.com/images/I/61gXZ2VqfdL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 1877.0,
    "price_original": 2299.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.6,
    "qtd_avaliacoes": 218,
    "coupon_code": null,
    "description": "<ul><li>Lavadora 15kg com a melhor lavagem e o menor consumo de água da categoria, segundo o Inmetro</li><li>Cor branca e voltagem de 127V, adequada para uso doméstico</li><li>Melhor lavagem e menor consumo de água da categoria, segundo o Inmetro</li></ul>",
    "informacoes_produto": {
      "Dimensões do produto": "69P x 60L x 105A centímetros",
      "Marca": "Panasonic",
      "Capacidade": "15 quilogramas",
      "Características especiais": "Sistema Ciclone de lavagem sem agitador, Smartsense",
      "Local de acesso": "Carga frontal"
    },
    "affiliate_url": "https://www.amazon.com.br/Panasonic-M%C3%A1quina-Lavar-Branca-NA-F150B1W/dp/B00HGNXC8Q?ref=dlx_deals_dg_dcl_B00HGNXC8Q_dt_sl14_88_pi&pf_rd_r=2MVQMGMQZXHE0GEQ6KKX&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B0DGVS763S",
    "title": "Balança Digital Bioimpedância Premium Bluetooth com App Saúde iOS Android para IMC Gordura Corporal Massa Muscular Massa Óssea Água Corporal Taxa Metabólica BMR Alta Precisão Vidro Temperado LED Luxo",
    "image": "https://m.media-amazon.com/images/I/51dktOgnYQL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 27.9,
    "price_original": 29.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.6,
    "qtd_avaliacoes": 6047,
    "coupon_code": null,
    "description": "<ul><li>✅ Monitore até 13 indicadores corporais em segundos – gordura visceral, IMC, massa muscular, água corporal e muito mais!</li><li>📱 Conectividade Bluetooth com app gratuito – visualize sua evolução em tempo real no celular (Android e iOS).</li><li>🎯 Ideal para quem quer emagrecer, ganhar massa ou manter a saúde em dia – resultados visíveis com dados precisos.</li><li>⚖️ Suporta até 140kg com sensores de alta precisão – medições confiáveis, mesmo com pequenas variações.</li><li>🧠 Tecnologia de bioimpedância profissional – usada por nutricionistas e academias para avaliações completas.</li><li>💎 Design premium com vidro temperado e visor LED – elegante, seguro e combina com qualquer ambiente.</li><li>🔋 Economia de energia com desligamento automático – funciona com 2 pilhas AAA (não inclusas).</li><li>🛡️ Sistema inteligente com alertas de sobrepeso e bateria fraca – segurança total para o uso diário.</li><li>👨‍👩‍👧‍👦 Perfeita para toda a família – compartilhe o uso com diferentes perfis no app e acompanhe todos.</li><li>🚀 Transforme sua rotina com dados reais e clareza total – tenha o controle do seu corpo na palma da mão!</li></ul>",
    "informacoes_produto": {
      "Marca": "Genérico",
      "Tipo de visor": "LED",
      "Limite de peso": "1 Quilogramas",
      "Fator de forma": "Portátil",
      "Material": "Vidro temperado"
    },
    "affiliate_url": "https://www.amazon.com.br/Bioimped%C3%A2ncia-Bluetooth-Controle-Completo-Corporal/dp/B0DGVS763S?ref=dlx_deals_dg_dcl_B0DGVS763S_dt_sl14_88_pi&pf_rd_r=2MVQMGMQZXHE0GEQ6KKX&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B0GHP4NL1J",
    "title": "Kit Rapunzel (Shampoo + Tônico + Milk Spray) - Lola From Rio",
    "image": "https://m.media-amazon.com/images/I/41OcWO275YL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 58.52,
    "price_original": 119.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 427,
    "coupon_code": null,
    "description": "<ul><li>Estimula o crescimento capilar, reduz a queda dos fios e nutre o couro cabeludo com fórmula vegana, cruelty-free e livre de sulfatos e silicones.</li><li>Kit composto por Shampoo, Tônico e Milk Spray com embalagens multicoloridas, da linha Rapunzel da marca Lola From Rio.</li><li>Fórmula leve e não oleosa indicada para uso diário, sem pesar os fios, mantendo a hidratação e o equilíbrio natural do couro cabeludo.</li></ul>",
    "informacoes_produto": {
      "Tipo de material livre": "Livre de sulfato",
      "Forma do produto": "Líquido",
      "Marca": "Lola",
      "Tipo de cabelo": "Cacheado, Danificado, Normal, Opaco, Todos"
    },
    "affiliate_url": "https://www.amazon.com.br/Rapunzel-Shampoo-T%C3%B4nico-Milk-Spray/dp/B0GHP4NL1J?ref=dlx_deals_dg_dcl_B0GHP4NL1J_dt_sl14_88_pi&pf_rd_r=W4XS7QFQ54H10VPE6BKR&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B0DKVJ1HWB",
    "title": "Lola Cosmetics Kit Cronograma Capilar Be(m) Dita Ghee - 3 Produtos",
    "image": "https://m.media-amazon.com/images/I/71K-GAoX50L._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 38.8,
    "price_original": 69.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 6337,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/FEIRA-CRONOLOLA-Cronograma-Capilar-Produtos/dp/B0DKVJ1HWB?ref=dlx_deals_dg_dcl_B0DKVJ1HWB_dt_sl14_88_pi&pf_rd_r=W4XS7QFQ54H10VPE6BKR&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B0FXH6Y9G8",
    "title": "Berço Portátil Bebê Acoplado Co-Bed Connect Maxi baby (Grafite)",
    "image": "https://m.media-amazon.com/images/I/51ougekSbcL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 399.9,
    "price_original": 629.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.5,
    "qtd_avaliacoes": 69,
    "coupon_code": null,
    "description": "<ul><li>- Idade Recomendada: A Partir de 0 Meses - Peso Máximo suportado: até 9 kg</li><li>- Estrutura de aço carbono durável e leve - Tecido de linho respirável, elegante e fácil de limpar</li><li>- Rodas universais com freio, garantindo mobilidade segura - Altura regulável em três posições</li><li>- Pode ser acoplado à cama dos pais - Função berço com balanço automático manual - Armazenamento dobrável e removível, ideal para viagens</li><li>- Inclui mosquiteiro, colchonete e cesto inferior organizador - Função Anti-Refluxo: Eleve um dos lados para evitar que o bebe vomite ou engasgue - Disponível nas cores: Cinza Claro, Cinza Escuro</li></ul>",
    "informacoes_produto": {
      "Cor": "Grafite",
      "Marca": "Maxi Baby",
      "Dimensões do produto": "92C x 68L x 85A centímetros",
      "Montagem necessária": "Sim",
      "Peso do produto": "7,1 Quilogramas"
    },
    "affiliate_url": "https://www.amazon.com.br/Port%C3%A1til-Acoplado-Connect-Maxi-Grafite/dp/B0FXH6Y9G8?ref=dlx_deals_dg_dcl_B0FXH6Y9G8_dt_sl14_88_pi&pf_rd_r=2MVQMGMQZXHE0GEQ6KKX&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B0DM6VH5KF",
    "title": "Samsung Ar-condicionado Split Inverter WindFree AI 12.000 BTUs Frio Sem Vento AR12DYFAAWKNAZ 220V",
    "image": "https://m.media-amazon.com/images/I/61SqDV4ba2L._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 2199.0,
    "price_original": 3929.31,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": null,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Samsung-Ar-condicionado-Inverter-WindFree-AR12DYFAAWKNAZ/dp/B0DM6VH5KF?ref=dlx_deals_dg_dcl_B0DM6VH5KF_dt_sl14_88_pi&pf_rd_r=2MVQMGMQZXHE0GEQ6KKX&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": true
  },
  {
    "asin": "B0C15434GB",
    "title": "Samsung Smart TV QLED 32\" Full HD QN32LS03C - Gaming Hub, Tela Matte, Modo Arte, Suporte de parede incluso",
    "image": "https://m.media-amazon.com/images/I/61oZi8WSqyL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 1799.0,
    "price_original": 2039.15,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.6,
    "qtd_avaliacoes": 621,
    "coupon_code": null,
    "description": "<ul><li>Tela Matte, Design slim, Suporte de parede slim incluso, Única Conexão, Molduras customizáveis, Modo Arte</li><li>Sistema operacional Tizen, Alexa Integrado</li><li>Cor do produto: Preto</li><li>Tamanho do produto: 32\"</li><li>Frequência: 60 Hz</li><li>Resolução: FULL HD (1,920 x 1,080)</li></ul>",
    "informacoes_produto": {
      "Tamanho da tela": "32 Polegadas",
      "Marca": "Samsung",
      "Tecnologia do visor": "Qled",
      "Resolução": "Full HD (1920 x 1080)",
      "Taxa de atualização": "50 Hz",
      "Características especiais": "Plana",
      "Componentes incluídos": "Cabo, manuais, controle",
      "Tecnologia de conectividade": "Bluetooth, HDMI, Wi-fi",
      "Proporção de tela": "16:9",
      "Dimensões do produto": "14,3P x 72,7L x 45,2A centímetros"
    },
    "affiliate_url": "https://www.amazon.com.br/Samsung-Smart-QLED-Full-QN32LS03C/dp/B0C15434GB?ref=dlx_deals_dg_dcl_B0C15434GB_dt_sl14_88_pi&pf_rd_r=2MVQMGMQZXHE0GEQ6KKX&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B000WLN7AM",
    "title": "Whisky Bourbon Maker's Mark 750ml",
    "image": "https://m.media-amazon.com/images/I/7199P9zzMGL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 119.9,
    "price_original": 145.33,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 3373,
    "coupon_code": null,
    "description": "<ul><li>Com coloração âmbar, laranja-amarelada, o bourbon tornou-se um dos destilados mais apreciados no mundo.</li><li>Diferentemente da composição do whisky tradicional, o Maker’s Mark não possui centeio na sua formulação, e sim, trigo doce e vermelho de inverno, milho e cevada.</li><li>O sucesso é fruto de um processo produtivo minucioso, que segue à risca os padrões de qualidade.</li><li>A produção é feita em baixa escala, em lotes individuais que não ultrapassam 19 barris por lote.</li><li>O Maker’s Mark é envelhecido por cerca de seis anos, depois de engarrafado é então selado em uma garrafa de forma única e selada com a cera vermelha na rolha.</li></ul>",
    "informacoes_produto": {
      "Marca": "Maker's Mark",
      "Tipo de álcool": "Bourbon",
      "Sabor": "Chocolate",
      "Contagem de unidades": "750.0 Mililitro",
      "Número de itens": "1"
    },
    "affiliate_url": "https://www.amazon.com.br/Whiskey-MakerS-Mark-Makers-Sabor/dp/B000WLN7AM?ref=dlx_deals_dg_dcl_B000WLN7AM_dt_sl14_88_pi&pf_rd_r=W4XS7QFQ54H10VPE6BKR&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B0D7NZ3N7P",
    "title": "L'Oréal Professionnel Máscara Absolut Repair Molecular, Repara os Danos & Recupera a Força, Maciez & Desembaraço, Para cabelos danificados e muito danificados",
    "image": "https://m.media-amazon.com/images/I/61i31s5HNkL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 160.0,
    "price_original": 249.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.6,
    "qtd_avaliacoes": 4804,
    "coupon_code": null,
    "description": "<ul><li>Absolut Repair Molecular. Repara 2 anos de danos em um uso. Pela primeira vez, L'Oréal Advanced Research conseguiu decompor peptídeos, para injetar seus componentes separadamente na fibra.</li><li>Uma vez dentro, eles reconstroem a estrutura molecular do cabelo.</li><li>Esta máscara concentrada patenteada, formulada com ligantes peptídicos + 5 aminoácidos, repara 2 anos de danos e restaura as camadas moleculares do cabelo.</li></ul>",
    "informacoes_produto": {
      "Marca": "L'Oréal Professionnel Paris",
      "Forma do produto": "Creme",
      "Característica do material": "Reciclável",
      "Tipo de cabelo": "Danificado"
    },
    "affiliate_url": "https://www.amazon.com.br/Professionnel-Molecular-Recupera-Desembara%C3%A7o-danificados/dp/B0D7NZ3N7P?ref=dlx_deals_dg_dcl_B0D7NZ3N7P_dt_sl14_88_pi&pf_rd_r=2MVQMGMQZXHE0GEQ6KKX&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B0B7SGQVT2",
    "title": "L'Oréal Professionnel Serie Expert NutriOil Máscara de Tratamento de Nutrição com Óleo de Soja para Cabelos Secos e Sem Brilho, para Força e Maciez 250g",
    "image": "https://m.media-amazon.com/images/I/419XkaLMgjL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 125.87,
    "price_original": 164.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 2056,
    "coupon_code": null,
    "description": "<ul><li>Máscara de nutrição para cabelos secos e sem brilho, com 250g para complementar seu cronograma capilar.</li><li>Sua fórmula sem silicone com Óleo de Soja promove força, proteção e reduz a porosidade de cabelos fracos e quebradiços.</li><li>Com uma textura leve, nutre profundamente sem pesar, deixando os cabelos com um toque sedoso e muito macio.</li><li>Garante uma transformação instantânea, com fios mais fáceis de desembaraçar e protegidos contra a quebra.</li><li>Conquiste cabelos 5x mais fortes, 2x mais macios e com muito mais brilho com este tratamento profissional.</li></ul>",
    "informacoes_produto": {
      "Marca": "L'Oréal Professionnel Paris",
      "Forma do produto": "Creme",
      "Característica do material": "Sustentável",
      "Tipo de cabelo": "Seco",
      "Vantagens do produto": "Cabelos 5x mais fortes, 2x mais macios e com muito mais brilho com este tratamento profissional."
    },
    "affiliate_url": "https://www.amazon.com.br/tratamento-NutriOil-nutri%C3%A7%C3%A3o-enriquecido-Professionnel/dp/B0B7SGQVT2?ref=dlx_deals_dg_dcl_B0B7SGQVT2_dt_sl14_88_pi&pf_rd_r=2MVQMGMQZXHE0GEQ6KKX&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B09GSQMVJS",
    "title": "L'Oréal Professionnel Inforcer Shampoo Fortificante Antiqueda por Quebra, Crescimento Saudável Para Cabelos Frágeis e Quebradiços Com Biotina e Vitamina B6, 300ml",
    "image": "https://m.media-amazon.com/images/I/51TvgvfNA9L._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 67.4,
    "price_original": 116.9,
    "parcelamento": "Em até 12x de R$ 6,22 com juros",
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "<ul><li>Um tratamento em shampoo que limpa, fortalece e proporciona uma ação anti-quebra instantânea nos fios.</li><li>Enriquecido com Biotina e Vitamina B6, que estimulam o crescimento saudável e o metabolismo de proteínas.</li><li>Leva nutrientes à fibra capilar, promovendo força instantânea e prevenindo o ressecamento e a quebra.</li><li>Com o uso contínuo, os cabelos se tornam mais resistentes, com menos queda e com um crescimento visível.</li><li>Conquiste cabelos suplementados com força, nutridos, resistentes e com o crescimento saudável que você deseja.</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/LOr%C3%A9al-Professionnel-Fortificante-Anti-Quebra-Quebradi%C3%A7os/dp/B09GSQMVJS?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B097RYMQZ5",
    "title": "Fralda Pom Pom Protek Proteção de Mãe Hiper M 86 Unidades",
    "image": "https://m.media-amazon.com/images/I/71p+Zbia21L._AC_SL1500_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 54.49,
    "price_original": 77.37,
    "parcelamento": "Em até 12x de R$ 5,03 com juros",
    "tem_selo_prime": false,
    "avaliacao": 4.6,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "<ul><li>Contém loção hidratante com extratos naturais que hidratam e protegem auxiliando na prevenção de irritação da pele do bebê.</li><li>Canal superabsorvente que garante a pele do seu bebê sequinha 2x mais rápido;</li><li>Benefício do uso contínuo: quanto mais o bebê usar a fralda Pom Pom Derma Protek mais hidratada sua pele ficará.</li><li>Produto único e superior com formulação exclusiva da Pom Pom.</li><li>Parceria inédita com a Fisher Price, marca reconhecida por qualidade e segurança em seus produtos.</li><li>Contém loção hidratante com extratos naturais que hidratam e protegem auxiliando na prevenção de irritação da pele do bebê.</li><li>Canal superabsorvente que garante a pele do seu bebê sequinha 2x mais rápido;</li><li>Benefício do uso contínuo: quanto mais o bebê usar a fralda Pom Pom Derma Protek mais hidratada sua pele ficará.</li><li>Produto único e superior com formulação exclusiva da Pom Pom.</li><li>Parceria inédita com a Fisher Price, marca reconhecida por qualidade e segurança em seus produtos.</li><li>Tamanho RN (Pacote de 18)</li><li>M (Pacote de 48)</li><li>L (Pacote de 24)</li><li>L (Pacote de 68)</li><li>XL (Pacote de 20)</li><li>2XL (Pacote de 30)</li><li>Tamanho P (Pacote de 30)</li><li>Tamanho XG (Pacote de 38)</li><li>Tamanho P (Pacote de 54)</li><li>M (28 Contagem)</li><li>M (86 Contagem)</li><li>XL (60 Contagem)</li><li>Tamanho XXG</li><li>18</li><li>20</li><li>24</li><li>28</li><li>30</li><li>38</li><li>48</li><li>54</li><li>60</li><li>68</li><li>86</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Fralda-Pom-Protek-Prote%C3%A7%C3%A3o-Hiper/dp/B097RYMQZ5?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B07FPW95CM",
    "title": "Jameson - Whiskey Irlandês, 750 ml",
    "image": "https://m.media-amazon.com/images/I/51syfbaTceL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 69.08,
    "price_original": 130.0,
    "parcelamento": "Em até 12x de R$ 6,38 com juros",
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "<ul><li>Sabor suave e equilibrado com toque adocicado</li><li>Destilado triplo de alta qualidade</li><li>Ideal para drinks ou puro</li><li>Garrafa elegante e tradicional</li><li>Whiskey irlandês reconhecido mundialmente</li><li>Sabor suave e equilibrado com toque adocicado</li><li>Destilado triplo de alta qualidade</li><li>Ideal para drinks ou puro</li><li>Garrafa elegante e tradicional</li><li>Whiskey irlandês reconhecido mundialmente</li><li>750 ml (Pacote de 1)</li><li>1000ml</li><li>A BEBIDA ALCOÓLICA PODE CAUSAR DEPENDÊNCIA QUÍMICA E, EM EXCESSO, PROVOCA GRAVES MALES À SAÚDE. A VENDA DE BEBIDAS ALCOÓLICAS É PROIBIDA PARA MENORES DE 18 ANOS. BEBA COM MODERAÇÃO.</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Jameson-Whisky-750ml/dp/B07FPW95CM?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B0CSPRNRZC",
    "title": "MSI GeForce RTX 3050 LP 6G OC (6GB GDDR6/PCI Express 4.0/1492MHz/14000MHz/Perfil baixo)",
    "image": "https://m.media-amazon.com/images/I/71Z9DLS29FL._AC_SL1500_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 999.0,
    "price_original": 1641.57,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "<ul><li>Ventilador duplo: dois ventiladores e um enorme dissipador de calor garantem uma experiência fresca e silenciosa para você.</li><li>MSI Afterburner: o melhor software de overclocking com opções avançadas de controle e monitor de hardware em tempo real.</li><li>PCB personalizado: O PCB personalizado foi projetado com circuitos endurecidos e roteamento de rastreamento otimizado para desempenho e confiabilidade.</li><li>MSI Centro: O software exclusivo MSI Centre permite monitorar, ajustar e otimizar os produtos MSI em tempo real.</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/MSI-GeForce-Express-1492MHz-14000MHz/dp/B0CSPRNRZC?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": true
  },
  {
    "asin": "B0D216Q2NR",
    "title": "Ar Condicionado Split Hi Wall R32 LG Dual Inverter Voice +AI 18000 BTU/h Frio S3-Q18KL31B – 220 Volts",
    "image": "https://m.media-amazon.com/images/I/41LEG77cCPL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 3249.0,
    "price_original": 3499.0,
    "parcelamento": "ou R$ 3.249,00 em até 12x de R$ 270,75 sem juros",
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "<ul><li>Ar-Condicionado Split LG Dual Inverter Voice R-32 +AI R-32 Os equipamentos de climatização estão ficando cada vez mais tecnológicos, facilitando o seu uso e a sua rotina. O ar-condicionado split LG dual inverter voice é ideal para quem quer refrescar os ambientes menores com mais conforto e bem-estar. O aparelho conta com Wi-fi integrado e pronto para usar, além de possuir gás ecológico R-32.</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Condicionado-Split-LG-Inverter-S3-Q18KL31B/dp/B0D216Q2NR?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B0GXX1CNPX",
    "title": "Guarda-roupa Casal com Espelho 6 Portas 4 Gavetas Araplac Braga",
    "image": "https://m.media-amazon.com/images/I/514R1MwvFJL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 1099.9,
    "price_original": 1249.9,
    "parcelamento": "ou R$ 1.099,90 em até 12x de R$ 91,75 sem juros",
    "tem_selo_prime": false,
    "avaliacao": 5.0,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "<ul><li>Estrutura: MDP</li><li>Revestimento: Verniz UV</li><li>Gavetas: 4 gavetas</li><li>Pintura interna na mesma cor do exterior (acabamento total).</li><li>Cabideiros metálicos que suportam casacos pesados e ternos.</li><li>Estrutura: MDP</li><li>Revestimento: Verniz UV</li><li>Gavetas: 4 gavetas</li><li>Pintura interna na mesma cor do exterior (acabamento total).</li><li>Cabideiros metálicos que suportam casacos pesados e ternos.</li><li>Freijo e Baunilha</li><li>freijo e carbono</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Guarda-roupa-Espelho-Portas-Gavetas-Araplac/dp/B0GXX1CNPX?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B07FN1MZBH",
    "title": "Controle Dualshock 4 - PlayStation 4 - Preto",
    "image": "https://m.media-amazon.com/images/I/61kwdPH8+xL._AC_SL1500_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 249.0,
    "price_original": 349.9,
    "parcelamento": "ou R$ 249,00 em até 6x de R$ 41,50 sem juros",
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "<ul><li>Revolucionário, intuitivo e preciso: o controle sem fio DualShock4 para o sistema PlayStation4 define esta geração de jogos, combinando recursos revolucionários e conforto com controles precisos e intuitivos.</li><li>Controle preciso: o toque, formato e a sensibilidade dos controles analógicos e botões com gatilho do DualShock4 oferecem aos jogadores conforto e controle absolutos em todos os jogos para PlayStation4.</li><li>Compartilhamento em suas mãos: o botão SHARE facilita o compartilhamento dos seus melhores momentos nos jogos, basta pressionar um botão. Faça upload de vídeos de gameplay e capturas de tela diretamente do seu sistema ou transmita seu gameplay ao vivo, tudo isso sem afetar o andamento do jogo.</li><li>Recursos inovadores: recursos revolucionários, como o touch pad, a barra de luz e o alto-falante integrados proporcionam formas incríveis de jogar e interagir com seus jogos, e seu conector de áudio de 3,5 mm oferece uma prática solução de áudio pessoal para os jogadores que preferirem jogar com mais privacidade.</li><li>Recarga eficiente: é fácil recarregar o controle sem fio DualShock4, basta conectá-lo ao seu sistema PlayStation4 (mesmo em modo de espera), ou qualquer carregador padrão com uma porta micro USB</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Controle-Dualshock-PlayStation-4-Preto/dp/B07FN1MZBH?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B0DXQC6MDM",
    "title": "Stanley - Garrafa de água Aerolight Fast Flow, garrafa isolada a vácuo para bebidas frias, aço inoxidável leve, 710 ml, Rose Quartz",
    "image": "https://m.media-amazon.com/images/I/410rzekdYXL._AC_SL1200_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 246.49,
    "price_original": 309.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "<ul><li>LEVE E À PROVA DE VAZAMENTOS - Fabricada com a tecnologia AeroLight, esta garrafa é 33% mais leve do que o aço inoxidável normal, garantindo que a sua bebida não sofra vazamentos durante o dia, desde os treinos até o caminho para o trabalho ou faculdade.</li><li>MATE SUA SEDE RÁPIDO – A ampla abertura na parte superior permite uma hidratação rápida e fácil preenchimento com gelo, para que você possa desfrutar de suas bebidas sem demora.</li><li>EXCELENTE ISOLAMENTO - O isolamento a vácuo de parede dupla mantém as bebidas geladas durante 10 horas e frias até 2 dias.</li><li>IDEAL PARA UM ESTILO DE VIDA ATIVO – Possui uma tampa Fast Flow à prova de vazamentos e uma alça para fácil transporte. É lavável na máquina de lavar louça para fácil limpeza e também conta com um suporte integrado para a tampa na alça para mantê-la segura, tornando-se a companheira perfeita para suas aventuras ativas.</li><li>STANLEY - Com uma rica história de 100 anos, a marca Stanley nos trouxe o isolamento a vácuo e revolucionou a maneira como consumimos bebidas. Do quente ao frio, os produtos Stanley são icônicos, duráveis e feitos para as aventuras modernas. Prepare-se para começar a sua.</li><li>LEVE E À PROVA DE VAZAMENTOS - Fabricada com a tecnologia AeroLight, esta garrafa é 33% mais leve do que o aço inoxidável normal, garantindo que a sua bebida não sofra vazamentos durante o dia, desde os treinos até o caminho para o trabalho ou faculdade.</li><li>MATE SUA SEDE RÁPIDO – A ampla abertura na parte superior permite uma hidratação rápida e fácil preenchimento com gelo, para que você possa desfrutar de suas bebidas sem demora.</li><li>EXCELENTE ISOLAMENTO - O isolamento a vácuo de parede dupla mantém as bebidas geladas durante 10 horas e frias até 2 dias.</li><li>IDEAL PARA UM ESTILO DE VIDA ATIVO – Possui uma tampa Fast Flow à prova de vazamentos e uma alça para fácil transporte. É lavável na máquina de lavar louça para fácil limpeza e também conta com um suporte integrado para a tampa na alça para mantê-la segura, tornando-se a companheira perfeita para suas aventuras ativas.</li><li>STANLEY - Com uma rica história de 100 anos, a marca Stanley nos trouxe o isolamento a vácuo e revolucionou a maneira como consumimos bebidas. Do quente ao frio, os produtos Stanley são icônicos, duráveis e feitos para as aventuras modernas. Prepare-se para começar a sua.</li><li>Ash</li><li>Azure Stripes</li><li>Black</li><li>Citron</li><li>Cream Ash Stripes</li><li>Cream Lilac Stripes</li><li>Cream Rose Gold</li><li>Flow Heather</li><li>Lavender</li><li>Lilac</li><li>Mint</li><li>Passion Pink</li><li>Polar</li><li>Pomelo</li><li>Rose Quartz</li><li>Rose Quartz Glow</li><li>Terracotta</li><li>Tigerlily</li><li>Tropical Teal</li><li>Vivid Violet</li><li>710 ml</li><li>1100 ml</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Stanley-Garrafa-Aerolight-garrafa-inoxid%C3%A1vel/dp/B0DXQC6MDM?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B0GYQF5DPD",
    "title": "Mesa Dobrável 1,80m Portátil Preta Tipo Maleta com Alça – Resistente e Leve, Ideal para Camping, Praia, Jardim, Festas e Área Gourmet Interna ou Externa",
    "image": "https://m.media-amazon.com/images/I/6118UighFQL._AC_SL1254_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 206.91,
    "price_original": 269.9,
    "parcelamento": "ou R$ 206,91 em até 6x de R$ 34,51 sem juros",
    "tem_selo_prime": false,
    "avaliacao": 4.2,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "<ul><li>Praticidade e Versatilidade no Seu Dia a Dia Tenha uma mesa ampla e funcional em qualquer lugar com montagem rápida e sem ferramentas. Estrutura dobrável tipo maleta facilita o transporte e armazenamento. Ideal para quem busca praticidade em eventos, viagens ou uso doméstico</li><li>Estrutura Resistente e Durável Fabricada com tampo reforçado e pés em material resistente, suporta uso frequente sem perder estabilidade. Design robusto com travas de segurança. Perfeita para quem precisa de durabilidade em ambientes internos e externos</li><li>Design Inteligente e Portátil Sistema dobrável compacto com alça integrada permite levar facilmente para qualquer lugar. Ocupa pouco espaço quando fechada. Ideal para camping, praia, churrascos e festas</li><li>Segurança e Estabilidade Garantidas Conta com sistema de travamento seguro que evita fechamentos acidentais durante o uso. Base firme e nivelada proporciona maior confiança. Perfeito para quem prioriza segurança e conforto</li><li>Conforto e Experiência Completa Superfície ampla de 1,80m acomoda várias pessoas com conforto. Ideal para refeições, reuniões, eventos e uso profissional. Excelente escolha para quem busca praticidade com estilo e funcionalidade.</li><li>Praticidade e Versatilidade no Seu Dia a Dia Tenha uma mesa ampla e funcional em qualquer lugar com montagem rápida e sem ferramentas. Estrutura dobrável tipo maleta facilita o transporte e armazenamento. Ideal para quem busca praticidade em eventos, viagens ou uso doméstico</li><li>Estrutura Resistente e Durável Fabricada com tampo reforçado e pés em material resistente, suporta uso frequente sem perder estabilidade. Design robusto com travas de segurança. Perfeita para quem precisa de durabilidade em ambientes internos e externos</li><li>Design Inteligente e Portátil Sistema dobrável compacto com alça integrada permite levar facilmente para qualquer lugar. Ocupa pouco espaço quando fechada. Ideal para camping, praia, churrascos e festas</li><li>Segurança e Estabilidade Garantidas Conta com sistema de travamento seguro que evita fechamentos acidentais durante o uso. Base firme e nivelada proporciona maior confiança. Perfeito para quem prioriza segurança e conforto</li><li>Conforto e Experiência Completa Superfície ampla de 1,80m acomoda várias pessoas com conforto. Ideal para refeições, reuniões, eventos e uso profissional. Excelente escolha para quem busca praticidade com estilo e funcionalidade.</li><li>✔ Estrutura resistente e durável para uso interno e externo</li><li>✔ Sistema dobrável compacto com alça para transporte fácil</li><li>✔ Montagem rápida, sem necessidade de ferramentas</li><li>✔ Superfície espaçosa ideal para várias pessoas</li><li>✔ Perfeita para festas, camping, praia, jardim ou uso profissional</li><li>Branca</li><li>Marrom</li><li>Preto</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Mesa-Dobr%C3%A1vel-Port%C3%A1til-Preta-Maleta/dp/B0GYQF5DPD?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B092V9M66J",
    "title": "Fralda Bigfral Derma Plus Econômica G 16 Unidades",
    "image": "https://m.media-amazon.com/images/I/719Wfl-X7lL._AC_SL1500_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 46.48,
    "price_original": 76.26,
    "parcelamento": "Em até 12x de R$ 4,29 com juros",
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "<ul><li>Rápida absorção. Evitando que a umidade fique em contato com a pele por períodos prolongados</li><li>Extratos naturais hidratantes. Exclusiva formula com extratos naturais que mantém a pele hidratada</li><li>Ajuda a prevenir irritações. Desenvolvida especialmente para ajudar a prevenir irritações na pele</li><li>Barreiras antivazamento. Proporciona proteção extra contra vazamentos, garantindo sensação de conforto e segurança</li><li>Sistema antiodor. Sistema que neutraliza o odor da urina, contribuindo para seu bem-estar</li><li>Rápida absorção. Evitando que a umidade fique em contato com a pele por períodos prolongados</li><li>Extratos naturais hidratantes. Exclusiva formula com extratos naturais que mantém a pele hidratada</li><li>Ajuda a prevenir irritações. Desenvolvida especialmente para ajudar a prevenir irritações na pele</li><li>Barreiras antivazamento. Proporciona proteção extra contra vazamentos, garantindo sensação de conforto e segurança</li><li>Sistema antiodor. Sistema que neutraliza o odor da urina, contribuindo para seu bem-estar</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Fralda-Derma-Plus-Bigfral-Grande/dp/B092V9M66J?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B0DBN85QC1",
    "title": "Samsung Lavadora Digital Inverter WW11T Inox 11kg 127V",
    "image": "https://m.media-amazon.com/images/I/51KPNZgowTL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 2799.0,
    "price_original": 2999.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.6,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "<ul><li>Mais performance de lavagem, menos água e energia</li><li>Lavagem rápida de 15 minutos para pequenas cargas</li><li>Limpeza profunda com vapor eliminando 99,9% de bactérias</li><li>Diamond Drum: delicadeza e preservação dos tecidos</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Samsung-Lavadora-Digital-Inverter-WW11T/dp/B0DBN85QC1?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B07MR3H8NY",
    "title": "Idôle Lancôme - Perfume Feminino Eau de Parfum",
    "image": "https://m.media-amazon.com/images/I/41daLSoQiGL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 466.99,
    "price_original": 779.0,
    "parcelamento": "ou R$ 466,99 em até 9x de R$ 51,95 sem juros",
    "tem_selo_prime": false,
    "avaliacao": 4.5,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "<ul><li>UMA FRAGRÂNCIA EXCLUSIVA. Idôle é uma fragrância floral chipre clean com ingredientes exclusivos, como pétalas de rosa de Esparta da Turquia, rosa centifolia de Grasse, jasmim grandiflorum da Índia e uma nova nota clean and glow. Cada elemento foi escolhido com cuidado para criar uma experiência olfativa única e inspiradora.</li><li>INSPIRAÇÃO EM MULHERES PIONEIRAS. É uma fragrância que homenageia mulheres pioneiras, verdadeiros modelos a serem seguidos. Ela celebra a convicção absoluta de que todas têm o poder de mudar o mundo e realizar seus maiores sonhos.</li><li>O FRASCO DA LEVEZA. O frasco de Idôle é um dos mais finos do mundo, com apenas 15 milímetros de espessura. Seu acabamento em ouro rosado enfatiza sua estrutura geométrica e a torna fácil de manusear. As superfícies de vidro translúcido são tão finas que o líquido parece estar nas palmas das mãos.</li><li>ADAPTABILIDADE À ERA MODERNA. Idôle é uma criação atemporal projetada para se adaptar às novas tecnologias. Sua essência ressoa com mulheres que transcendem convenções e buscam o sucesso de maneiras únicas e inovadoras.</li><li>LANCÔME: SINÔNIMO DE ELEGÂNCIA. Fundada em 1935 por Armand Petitjean, em Paris, Lancôme é uma marca de renome mundial. Símbolo de excelência, sofisticação e inovação em fragrância. Sinta-se envolvida pela tradição e inovação da Lancôme.</li><li>UMA FRAGRÂNCIA EXCLUSIVA. Idôle é uma fragrância floral chipre clean com ingredientes exclusivos, como pétalas de rosa de Esparta da Turquia, rosa centifolia de Grasse, jasmim grandiflorum da Índia e uma nova nota clean and glow. Cada elemento foi escolhido com cuidado para criar uma experiência olfativa única e inspiradora.</li><li>INSPIRAÇÃO EM MULHERES PIONEIRAS. É uma fragrância que homenageia mulheres pioneiras, verdadeiros modelos a serem seguidos. Ela celebra a convicção absoluta de que todas têm o poder de mudar o mundo e realizar seus maiores sonhos.</li><li>O FRASCO DA LEVEZA. O frasco de Idôle é um dos mais finos do mundo, com apenas 15 milímetros de espessura. Seu acabamento em ouro rosado enfatiza sua estrutura geométrica e a torna fácil de manusear. As superfícies de vidro translúcido são tão finas que o líquido parece estar nas palmas das mãos.</li><li>ADAPTABILIDADE À ERA MODERNA. Idôle é uma criação atemporal projetada para se adaptar às novas tecnologias. Sua essência ressoa com mulheres que transcendem convenções e buscam o sucesso de maneiras únicas e inovadoras.</li><li>LANCÔME: SINÔNIMO DE ELEGÂNCIA. Fundada em 1935 por Armand Petitjean, em Paris, Lancôme é uma marca de renome mundial. Símbolo de excelência, sofisticação e inovação em fragrância. Sinta-se envolvida pela tradição e inovação da Lancôme.</li><li>25 ml</li><li>50 ml</li><li>100 ml</li><li>Refil</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Id%C3%B4le-Lanc%C3%B4me-Perfume-Feminino-Parfum/dp/B07MR3H8NY?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B0C6MZ861Q",
    "title": "Cooktop de Indução Quatro Bocas Eos Eci04ep 220v",
    "image": "https://m.media-amazon.com/images/I/51iDChXZhhL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 886.77,
    "price_original": 933.45,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "<ul><li>Cooktop de indução com 4 bocas, mais seguro e rápido que fogões tradicionais, com trava para crianças e desligamento automático</li><li>Design moderno com painel digital touch e superfície de vidro cerâmico preto de alta durabilidade, facilitando a limpeza</li><li>9 níveis de potência, função turbo para aquecimento rápido e timer de até 99 minutos para maior praticidade no preparo de alimentos</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Cooktop-Indu%C3%A7%C3%A3o-Quatro-Bocas-Eci04ep/dp/B0C6MZ861Q?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B0842XB4BN",
    "title": "Mochila Dell Gaming 140T, Compatível com notebooks de até 17\", Resistente à água, Painel frontal reflexivo, Vários compartimentos, Parte traseira em malha respirável, Preto",
    "image": "https://m.media-amazon.com/images/I/91PDPYo4jUL._AC_SL1500_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 199.0,
    "price_original": 279.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "<ul><li>ARMAZENAMENTO VERSÁTIL: Compartimento para notebook até 17”, bolso de malha com zíper, bolsos elásticos para garrafa ou guarda‑chuva, gancho para headset e porta‑canetas organizam seus acessórios.</li><li>RESISTÊNCIA À ÁGUA: Tecido resistente à água e capa de chuva integrada protegem o notebook gamer contra chuva, respingos e derramamentos acidentais.</li><li>CONFORTO NO TRANSPORTE: Três formas de uso: alça superior reforçada, alça frontal de liberação rápida e alças de ombro acolchoadas em S. Painel traseiro em malha respirável.</li><li>MAIOR VISIBILIDADE E SEGURANÇA: O painel frontal reflexivo em tom arco‑íris melhora a visibilidade em ambientes com pouca luz, trazendo segurança em caminhadas noturnas, aeroportos e áreas urbanas.</li><li>GARANTIA: Garantia limitada de três anos com serviço de troca avançada para substituição rápida em caso de defeito.</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Mochila-Dell-Notebook-Resistente-Integrada/dp/B0842XB4BN?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B0F66VR4YW",
    "title": "Ograx-3 500 Suplemento Para Cães e Gatos 90 Cápsulas 65,7g | 65,7g",
    "image": "https://m.media-amazon.com/images/I/51A3xCVjq2L._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 128.99,
    "price_original": 229.9,
    "parcelamento": "Em até 12x de R$ 12,03 com juros",
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "<ul><li>Suplemento para cães e gatos</li><li>Suplemento para cães e gatos</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Ograx-3-Suplemento-Para-Gatos-C%C3%A1psulas/dp/B0F66VR4YW?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "8542229177",
    "title": "Tempestade de Ônix: Sequência dos fenômenos mundiais Quarta Asa e Chama de Ferro (Série O Empyriano, Livro 3)",
    "image": "https://m.media-amazon.com/images/I/91915km0UdL._SL1500_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 69.64,
    "price_original": 109.9,
    "parcelamento": "Em até 12x de R$ 6,43 com juros",
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": null,
    "coupon_code": "LEIA20",
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Tempestade-%C3%94nix-Sequ%C3%AAncia-fen%C3%B4menos-Empyriano/dp/8542229177?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B0H37BN323",
    "title": "Robô Aspirador de Pó e Passa Pano KABUM! smart K1100 - Mapeia a Laser, 2 MOPs, até 10.000Pa, Alexa/Google, BT, 220v, Branco - KSAR110020BR",
    "image": "https://m.media-amazon.com/images/I/51bRJoeZO1L._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 1969.99,
    "price_original": 2199.99,
    "parcelamento": "ou R$ 1.969,99 em até 12x de R$ 164,23 sem juros",
    "tem_selo_prime": false,
    "avaliacao": 5.0,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "<ul><li>robô aspirador passa pano branco mop inteligente automação</li><li>Visão 360°: O Robô Aspirador KABUM! smart K1100 oferece uma visão completa do ambiente, permitindo mapeamento preciso e limpeza eficiente em todos os cantos.</li><li>Mapeamento a Laser: Equipado com um sistema de mapeamento a laser, ele reconhece cada centímetro do ambiente em tempo real para traçar as rotas mais eficientes.</li><li>robô aspirador passa pano branco mop inteligente automação</li><li>Visão 360°: O Robô Aspirador KABUM! smart K1100 oferece uma visão completa do ambiente, permitindo mapeamento preciso e limpeza eficiente em todos os cantos.</li><li>Mapeamento a Laser: Equipado com um sistema de mapeamento a laser, ele reconhece cada centímetro do ambiente em tempo real para traçar as rotas mais eficientes.</li><li>127V</li><li>220V</li><li>Branco</li><li>Preto</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Aspirador-Passa-KABUM-smart-K1100/dp/B0H37BN323?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B074LSL2VG",
    "title": "Morte Súbita Spray Reparação Total 250ml , Lola Cosmetics",
    "image": "https://m.media-amazon.com/images/I/710d9TP3IwL._AC_SL1500_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 21.94,
    "price_original": 54.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "<ul><li>result: Cabelo restaurado, com a saúde recuperada, além de hidratado, macio e com brilho</li><li>Cor do produto: Preto</li><li>Tamanho do produto: 250 ml (Pacote de 1)</li><li>Quantidade no pacote: 1</li><li>result: Cabelo restaurado, com a saúde recuperada, além de hidratado, macio e com brilho</li><li>Cor do produto: Preto</li><li>Tamanho do produto: 250 ml (Pacote de 1)</li><li>Quantidade no pacote: 1</li><li>Spray</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Lola-Cosmetics-Spray-Subita-Repara%C3%A7%C3%A3o/dp/B074LSL2VG?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B0B7SH8YPV",
    "title": "L'Oréal Professionnel NutriOil Leave-in, Hidratação e Nutrição Intensa para Cabelos Secos e Sem Brilho, com Óleo de Coco, Proteção Térmica e Antifrizz, 150ml",
    "image": "https://m.media-amazon.com/images/I/41YAXDAgkVL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 104.39,
    "price_original": 159.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "<ul><li>Este leave-in profissional é a solução ideal para cabelos secos e sem brilho, proporcionando nutrição profunda sem pesar os fios, ideal para complementar seu cronograma capilar.</li><li>Sua fórmula avançada é enriquecida com 1,5% de óleo de coco, que oferece ação umectante, fortalecendo a resistência da fibra capilar e promovendo maciez, brilho e movimento.</li><li>Desfrute de proteção térmica de até 230°C, protegendo os cabelos do calor de ferramentas e garantindo proteção antifrizz por até 24 horas.</li><li>Com sua ação umectante, o óleo de coco adere ao fio formando uma camada protetora na superfície Além de penetrar na fibra, fortalecendo a sua resistência e promovendo nutrição com maciez, brilho e movimento.</li><li>Contém: 1 Leave-in L'Oréal Professionnel NutriOil 150ml, para cabelos instantaneamente 4x mais macios e com muito mais brilho.</li><li>Este leave-in profissional é a solução ideal para cabelos secos e sem brilho, proporcionando nutrição profunda sem pesar os fios, ideal para complementar seu cronograma capilar.</li><li>Sua fórmula avançada é enriquecida com 1,5% de óleo de coco, que oferece ação umectante, fortalecendo a resistência da fibra capilar e promovendo maciez, brilho e movimento.</li><li>Desfrute de proteção térmica de até 230°C, protegendo os cabelos do calor de ferramentas e garantindo proteção antifrizz por até 24 horas.</li><li>Com sua ação umectante, o óleo de coco adere ao fio formando uma camada protetora na superfície Além de penetrar na fibra, fortalecendo a sua resistência e promovendo nutrição com maciez, brilho e movimento.</li><li>Contém: 1 Leave-in L'Oréal Professionnel NutriOil 150ml, para cabelos instantaneamente 4x mais macios e com muito mais brilho.</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/LOREAL-PROFESSIONNEL-NutriOil-nutri%C3%A7%C3%A3o-enriquecido/dp/B0B7SH8YPV?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B0D137TMRB",
    "title": "ONE DAY EXOSOME SHOT PORE SERUM 7500 30ml",
    "image": "https://m.media-amazon.com/images/I/71I6MkG0fyL._AC_SL1500_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 118.83,
    "price_original": 168.46,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.5,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "<ul><li>Sérum concentrado de regeneração intensa Tratamento diário com alta concentração de exossomos para revitalizar a pele, melhorar firmeza, textura e luminosidade.</li><li>Resultados visíveis de viço e uniformidade Auxilia na regeneração celular acelerada, deixando a pele mais firme, macia e com glow natural.</li><li>Tecnologia Exosome Shot 7500 Fórmula com 7.500 ppm de exossomos que atuam diretamente na renovação e vitalidade da pele.</li><li>Indicado para peles cansadas ou maduras Adequado para todos os tipos de pele, especialmente aquelas com sinais iniciais de envelhecimento ou opacidade.</li><li>Modo de uso Aplicar 2 a 3 pumps no rosto limpo, de manhã e/ou à noite. Durante o dia, usar protetor solar.</li><li>Sérum concentrado de regeneração intensa Tratamento diário com alta concentração de exossomos para revitalizar a pele, melhorar firmeza, textura e luminosidade.</li><li>Resultados visíveis de viço e uniformidade Auxilia na regeneração celular acelerada, deixando a pele mais firme, macia e com glow natural.</li><li>Tecnologia Exosome Shot 7500 Fórmula com 7.500 ppm de exossomos que atuam diretamente na renovação e vitalidade da pele.</li><li>Indicado para peles cansadas ou maduras Adequado para todos os tipos de pele, especialmente aquelas com sinais iniciais de envelhecimento ou opacidade.</li><li>Modo de uso Aplicar 2 a 3 pumps no rosto limpo, de manhã e/ou à noite. Durante o dia, usar protetor solar.</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/EXOSOME-SHOT-PORE-SERUM-7500/dp/B0D137TMRB?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B0F67HS3N7",
    "title": "Ralph Lauren Polo Sport Perfume Masculino, Fragrância Aromática Cítrica para Homens com Estilo de Vida Ativo, Eau de Toilette Refrescante e Energizante 100ml",
    "image": "https://m.media-amazon.com/images/I/615GjIDcMqL._AC_SL1500_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 219.99,
    "price_original": 399.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.5,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "<ul><li>Fragrância aromática que combina notas cítricas, aquáticas e amadeiradas para uma explosão de frescor intenso.</li><li>Assinatura olfativa ideal para o homem de estilo de vida ativo que busca uma fragrância jovem e vibrante.</li><li>Com notas marcantes de menta, limão e algas marinhas, é um verdadeiro concentrado de energia e vitalidade.</li><li>Proporciona uma sensação de bem-estar e limpeza que acompanha você durante todo o dia, em qualquer ocasião.</li><li>Um clássico atemporal que representa a força do esporte com o espírito jovem e otimista de Ralph Lauren.</li><li>Fragrância aromática que combina notas cítricas, aquáticas e amadeiradas para uma explosão de frescor intenso.</li><li>Assinatura olfativa ideal para o homem de estilo de vida ativo que busca uma fragrância jovem e vibrante.</li><li>Com notas marcantes de menta, limão e algas marinhas, é um verdadeiro concentrado de energia e vitalidade.</li><li>Proporciona uma sensação de bem-estar e limpeza que acompanha você durante todo o dia, em qualquer ocasião.</li><li>Um clássico atemporal que representa a força do esporte com o espírito jovem e otimista de Ralph Lauren.</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Masculino-Fragr%C3%A2ncia-Arom%C3%A1tica-Refrescante-Energizante/dp/B0F67HS3N7?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B0BGMD5LGF",
    "title": "Personal Fralda Baby Premium Pants G, 62 Unidades",
    "image": "https://m.media-amazon.com/images/I/51YPzh4uhaL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 81.98,
    "price_original": 116.89,
    "parcelamento": "Em até 12x de R$ 7,57 com juros",
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "<ul><li>Fácil de vestir e fácil de tirar</li><li>Super Macio como Toque de Algodão*</li><li>Rápida Absorção 3D Ultrarrespirável - Até 12hrs de Proteção</li><li>Ajuste Perfeito Não Aperta Barriguinha e Perninhas</li><li>Tecnologia Japonesa</li><li>Fácil de vestir e fácil de tirar</li><li>Super Macio como Toque de Algodão*</li><li>Rápida Absorção 3D Ultrarrespirável - Até 12hrs de Proteção</li><li>Ajuste Perfeito Não Aperta Barriguinha e Perninhas</li><li>Tecnologia Japonesa</li><li>M - 48 Unidades</li><li>M - 70 Unidades</li><li>XXG - 30 Unidades</li><li>XG - 34 Unidades</li><li>G - 42 Unidades</li><li>XG - 50 Unidades</li><li>G - 62 Unidades</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Fralda-Personal-Baby-Premium-Pants/dp/B0BGMD5LGF?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B0DNHGQHMY",
    "title": "Bettdow SmartWatch, relogio smartwatch com Ecrã tátil e Alexa, à prova d'água IP68, relogio feminino e masculino, com 100+ modo esportivo e recebimento de notificações(preto)",
    "image": "https://m.media-amazon.com/images/I/61jq8y1sVZL._AC_SL1500_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 126.71,
    "price_original": 186.0,
    "parcelamento": "ou R$ 126,71 em até 4x de R$ 31,70 sem juros",
    "tem_selo_prime": false,
    "avaliacao": 4.5,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "<ul><li>Relógio esportivo：Relógio esportivo, 100 modos de exercício regulares, suporte para de corrida, Yoga, pular corda, Futebol, natação e outros vários modos de exercício</li><li>AMAZON ALEXA : Bettdow smartwatch Defina alarmes e temporizadores, verifique o clima, obtenha traduções, controle seus dispositivos de casa inteligente, crie listas de compras e muito mais com o assistente de voz Amazon Alexa.</li><li>Chamada de voz Bluetooth: O relógio smartwatch adulto unissex não apenas exibe a hora, mas também pode fazer e receber chamadas e receber notificações de mensagens via Bluetooth.</li><li>IP68 à prova d'água: você pode usar o smartwatch masculino à prova d'água IP68 para lavar as mãos e tomar banho sem se preocupar com danos causados ​​pela água, atendendo melhor às suas necessidades diárias.</li><li>Bateria de longa duração: Relogio smartwatch aproveite o uso ininterrupto com até 48 horas de uso contínuo e até 7 dias de uso regular. No modo standby, a bateria dura até 30 dias.Além disso, o relógio é amplamente compatível com Android e iOS.</li><li>Relógio esportivo：Relógio esportivo, 100 modos de exercício regulares, suporte para de corrida, Yoga, pular corda, Futebol, natação e outros vários modos de exercício</li><li>AMAZON ALEXA : Bettdow smartwatch Defina alarmes e temporizadores, verifique o clima, obtenha traduções, controle seus dispositivos de casa inteligente, crie listas de compras e muito mais com o assistente de voz Amazon Alexa.</li><li>Chamada de voz Bluetooth: O relógio smartwatch adulto unissex não apenas exibe a hora, mas também pode fazer e receber chamadas e receber notificações de mensagens via Bluetooth.</li><li>IP68 à prova d'água: você pode usar o smartwatch masculino à prova d'água IP68 para lavar as mãos e tomar banho sem se preocupar com danos causados ​​pela água, atendendo melhor às suas necessidades diárias.</li><li>Bateria de longa duração: Relogio smartwatch aproveite o uso ininterrupto com até 48 horas de uso contínuo e até 7 dias de uso regular. No modo standby, a bateria dura até 30 dias.Além disso, o relógio é amplamente compatível com Android e iOS.</li><li>azul</li><li>branco</li><li>preto</li><li>rosa</li><li>roxo</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Bettdow-SmartWatch-smartwatch-recebimento-notifica%C3%A7%C3%B5es/dp/B0DNHGQHMY?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B07PNK7JSN",
    "title": "Vanish Tira Manchas Em Pó, Multi Power Oxi Action, para Roupas Coloridas Refil 2,5Kg",
    "image": "https://m.media-amazon.com/images/I/71oeDuf8dTL._AC_SL1500_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 80.5,
    "price_original": 109.59,
    "parcelamento": "Em até 12x de R$ 7,44 com juros",
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "<ul><li>Vanish pó para roupas coloridas: Remove manchas com segurança, deixando roupas limpas e cheirosas</li><li>Tira manchas eiciente na remoção de manchas em roupas coloridas, atua em apenas 30 segundos</li><li>Revive os tons das roupas, deixando as peças brancas até três tons mais claras</li><li>Vanish é compatível com sabão em pó, tornando-se a combinação perfeita para lavar roupas</li><li>Vanish é compatível com sabão em pó, tornando-se a combinação perfeita para lavar roupas</li><li>Vanish pó para roupas coloridas: Remove manchas com segurança, deixando roupas limpas e cheirosas</li><li>Tira manchas eiciente na remoção de manchas em roupas coloridas, atua em apenas 30 segundos</li><li>Revive os tons das roupas, deixando as peças brancas até três tons mais claras</li><li>Vanish é compatível com sabão em pó, tornando-se a combinação perfeita para lavar roupas</li><li>Vanish é compatível com sabão em pó, tornando-se a combinação perfeita para lavar roupas</li><li>Roupas Brancas</li><li>Roupas Coloridas</li><li>2.5 kg (Pacote de 1)</li><li>120g</li><li>240g</li><li>450g</li><li>1 kg (Pacote de 1)</li><li>400 g (Pacote de 1)</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Manchas-Action-Refil-Econ%C3%B4mico-Vanish/dp/B07PNK7JSN?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B0DJ9XGMTQ",
    "title": "ITS Imports Cadeira de Escritório Presidente Ergonômica Preta Encosto Mesh Reclinável 135 Graus Cadeira Giratória com Apoio de Cabeça Braços Ajustáveis Suporte Lombar Alta Densidade Confortável",
    "image": "https://m.media-amazon.com/images/I/61b3Yk+5NPL._AC_SL1254_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 299.0,
    "price_original": 359.0,
    "parcelamento": "ou R$ 299,00 em até 6x de R$ 49,85 sem juros",
    "tem_selo_prime": false,
    "avaliacao": 3.8,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "<ul><li>ERGONOMIA PREMIUM PARA SUA COLUNA: Diga adeus às dores nas costas com o design anatômico que molda sua postura. O encosto acompanha a curvatura natural da região lombar e dorsal, distribuindo o peso e aliviando a tensão muscular. Ideal para profissionais que buscam proteger a saúde da coluna durante longas jornadas de trabalho ou estudo.</li><li>TELA MESH ULTRA RESPIRÁVEL: Esqueça o calor excessivo e o incômodo do suor. O encosto em malha Mesh de alta densidade promove a circulação contínua do ar, mantendo suas costas frescas mesmo nos dias mais quentes. Une alta resistência mecânica e conforto térmico. Perfeito para quem valoriza um ambiente de trabalho sempre agradável.</li><li>APOIO DE CABEÇA AJUSTÁVEL: Proteja sua região cervical contra tensões e dores no pescoço. O suporte integrado e ajustável oferece o descanso ideal para os momentos de foco profundo ou relaxamento entre reuniões. Sinta a diferença de um ajuste que se adapta à sua altura. Essencial para quem passa horas focado na tela do computador.</li><li>BRAÇOS ARTICULÁVEIS E INTELIGENTES: Adapte seu espaço ao seu corpo, e não o contrário. Os apoios de braço possuem regulagem de inclinação inteligente, permitindo o encaixe perfeito sob a mesa ou o alinhamento correto para digitar sem forçar os ombros. Excelente para quem busca otimizar espaço e ganhar liberdade de movimento no home office.</li><li>INCLINAÇÃO SINCRONIZADA E RELAX: Alivie a pressão nas costas ao longo do dia com o sistema de reclinação integrada. O mecanismo permite inclinar o encosto de forma suave, oferecendo o ângulo perfeito para descansar a mente sem perder a estabilidade. Ideal para fazer pequenas pausas revigorantes e manter o rendimento lá no alto.</li><li>REGULAGEM DE ALTURA A GÁS: Encontre a posição perfeita de digitação com o ajuste milimétrico de altura do assento (44 cm a 54 cm do chão). O pistão a gás de alta performance garante movimentos suaves, amortecimento seguro e alta durabilidade para suportar o uso intenso diário. Perfeito para manter o alinhamento correto com o seu monitor.</li><li>BASE ALL-BLACK SILENCIOSA: Movimente-se pelo escritório com total liberdade e sem ruídos. A base giratória 360° reforçada de 65 cm possui rodízios em nylon que deslizam suavemente sem arranhar ou marcar o piso laminado ou porcelanato. O design todo em preto confere sofisticação moderna. Ideal para quartos e escritórios.</li><li>ERGONOMIA PREMIUM PARA SUA COLUNA: Diga adeus às dores nas costas com o design anatômico que molda sua postura. O encosto acompanha a curvatura natural da região lombar e dorsal, distribuindo o peso e aliviando a tensão muscular. Ideal para profissionais que buscam proteger a saúde da coluna durante longas jornadas de trabalho ou estudo.</li><li>TELA MESH ULTRA RESPIRÁVEL: Esqueça o calor excessivo e o incômodo do suor. O encosto em malha Mesh de alta densidade promove a circulação contínua do ar, mantendo suas costas frescas mesmo nos dias mais quentes. Une alta resistência mecânica e conforto térmico. Perfeito para quem valoriza um ambiente de trabalho sempre agradável.</li><li>APOIO DE CABEÇA AJUSTÁVEL: Proteja sua região cervical contra tensões e dores no pescoço. O suporte integrado e ajustável oferece o descanso ideal para os momentos de foco profundo ou relaxamento entre reuniões. Sinta a diferença de um ajuste que se adapta à sua altura. Essencial para quem passa horas focado na tela do computador.</li><li>BRAÇOS ARTICULÁVEIS E INTELIGENTES: Adapte seu espaço ao seu corpo, e não o contrário. Os apoios de braço possuem regulagem de inclinação inteligente, permitindo o encaixe perfeito sob a mesa ou o alinhamento correto para digitar sem forçar os ombros. Excelente para quem busca otimizar espaço e ganhar liberdade de movimento no home office.</li><li>INCLINAÇÃO SINCRONIZADA E RELAX: Alivie a pressão nas costas ao longo do dia com o sistema de reclinação integrada. O mecanismo permite inclinar o encosto de forma suave, oferecendo o ângulo perfeito para descansar a mente sem perder a estabilidade. Ideal para fazer pequenas pausas revigorantes e manter o rendimento lá no alto.</li><li>REGULAGEM DE ALTURA A GÁS: Encontre a posição perfeita de digitação com o ajuste milimétrico de altura do assento (44 cm a 54 cm do chão). O pistão a gás de alta performance garante movimentos suaves, amortecimento seguro e alta durabilidade para suportar o uso intenso diário. Perfeito para manter o alinhamento correto com o seu monitor.</li><li>BASE ALL-BLACK SILENCIOSA: Movimente-se pelo escritório com total liberdade e sem ruídos. A base giratória 360° reforçada de 65 cm possui rodízios em nylon que deslizam suavemente sem arranhar ou marcar o piso laminado ou porcelanato. O design todo em preto confere sofisticação moderna. Ideal para quartos e escritórios.</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Escrit%C3%B3io-Presidente-Estofamento-Reclin%C3%A1vel-Girat%C3%B3ria/dp/B0DJ9XGMTQ?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B0D6DT84JD",
    "title": "Bettdow Monitor Portatil 15,6'', FHD 1080P Monitor Portátil Conectado Com USB C Dupla/HDMI, IPS Extensor De Tela para Notebook com VESA e Funda Inteligente magnético, Plug and Play",
    "image": "https://m.media-amazon.com/images/I/71SfTDj9NmL._AC_SL1500_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 424.13,
    "price_original": 499.0,
    "parcelamento": "ou R$ 424,13 em até 9x de R$ 47,17 sem juros",
    "tem_selo_prime": false,
    "avaliacao": 4.5,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "<ul><li>Bettdow Monitor Portatil 15,6'', FHD 1080P Monitor Portátil Conectado Com USB C Dupla/HDMI, IPS Extensor De Tela para Notebook com VESA e Funda Inteligente magnético, Plug and Play</li><li>Monitor Portatil Full HD - monitor portatil para notebook de 15,6 polegadas com resolução de 1920 x 1080, tela IPS avançada brilhante com suporte para ângulo de visão total de 178°, ele renderiza cores precisas e brilhantes, atrai você para o vídeo ou jogo com cores realistas e detalhes incríveis. Ele pode reduzir efetivamente os danos da radiação de luz azul, sem cintilação, protege os olhos e torna mais fácil assistir por um longo tempo. Um segundo monitor para trabalhar em casa.</li><li>Porta Tipo C Dupla - Para Plug &amp; Play, o monitor usb-c BETTDOW 2 portas Tipo C com todos os recursos. Apenas um cabo USB Tipo C é necessário para conectar à fonte de alimentação e à transmissão do sinal de exibição. que suporta várias formas de conexão com seus laptops, PC, telefones, Macbooks, PS5/PS4, Xbox</li><li>Capa Durável e Inteligente: O extensor de tela portátil BETTDOW tem um material plástico durável e de alta qualidade, o que o faz mostrar uma textura fina e alta resistência. Tem capa inteligente de couro magnético que fornece proteção para toda a tela e é fácil de colocar o tela computador em pé.</li><li>Não procure mais!: Adquira já este screen extender, completo com capa magnética, 2 alto-falantes integrados para reproduzir áudio, cabo USB-C para USB-C, cabo Mini HDMI para HDMI.</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Bettdow-Portatil-Conectado-Inteligente-magn%C3%A9tico/dp/B0D6DT84JD?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "6584004406",
    "title": "Vade Mecum Saraiva Tradicional - 41ª Edição 2026",
    "image": "https://m.media-amazon.com/images/I/81HmyZ8mCzL._SL1500_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 179.0,
    "price_original": 309.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": null,
    "coupon_code": "LEIA20",
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Vade-Mecum-Saraiva-Tradicional-Edi%C3%A7%C3%A3o/dp/6584004406?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B0FLQCFY36",
    "title": "Freezer Vertical Eos 176 Litros Ecogelo Branco Efv250 110v",
    "image": "https://m.media-amazon.com/images/I/31+ushkyPrL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 1798.44,
    "price_original": 1899.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.1,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "<ul><li>Capacidade Bruta 198 Litros</li><li>Capacidade Líquida 176 Litros</li><li>Garantia do Compressor 10 anos</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Freezer-Vertical-Litros-Ecogelo-Branco/dp/B0FLQCFY36?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B0F6D2CWS7",
    "title": "Relógio Digital Feminino Masculino Smartwatch Inteligente Bluetooth, Full Touch a Prova d 'água IP68 com 120+ Modos de Exercício e Esporte, Preto",
    "image": "https://m.media-amazon.com/images/I/61oxx+xFfuL._AC_SL1500_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 107.99,
    "price_original": 119.99,
    "parcelamento": "ou R$ 107,99 em até 3x de R$ 36,01 sem juros",
    "tem_selo_prime": false,
    "avaliacao": 4.5,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "<ul><li>Atenda chamadas: Com o Watch FB025, é possível atender ou rejeitar chamadas diretamente do seu pulso, desde que haja conexão via Bluetooth com o seu celular</li><li>Bateria de Longa Duração: O smartwatch esportivo acompanha um cabo USB de carregamento rápido, bateria de 280 mAh, suporta de 7 dias de uso e mais de 15 dias em modo de espera após 2 horas de carga da bateria. Leve-o com você para viajar, caminhar, nadar e trabalhar, nunca se preocupe com a bateria acabando</li><li>IP68 à prova d'água e ampla compatibilidade: Um smartwatch à prova d'água projetado com tecnologia avançada IP68 que permite que você lave as mãos, tome banho e esportes aquáticos. Baixe e instale o aplicativo gratuito \" Da Fit\", ele sincronizará com seu telefone instantaneamente</li><li>Funcionalidades de Mensagens e Redes Sociais: O relógio possibilita a leitura de mensagens de plataformas como WhatsApp, Facebook, Twitter, entre outras. No entanto, não oferece a capacidade de responder a essas mensagens. Além disso, ele exibe notificações de redes sociais diretamente na tela do dispositivo</li><li>Contém: caixa de presente、carregador magnético、manual do usuário, garantia de dois meses</li><li>Atenda chamadas: Com o Watch FB025, é possível atender ou rejeitar chamadas diretamente do seu pulso, desde que haja conexão via Bluetooth com o seu celular</li><li>Bateria de Longa Duração: O smartwatch esportivo acompanha um cabo USB de carregamento rápido, bateria de 280 mAh, suporta de 7 dias de uso e mais de 15 dias em modo de espera após 2 horas de carga da bateria. Leve-o com você para viajar, caminhar, nadar e trabalhar, nunca se preocupe com a bateria acabando</li><li>IP68 à prova d'água e ampla compatibilidade: Um smartwatch à prova d'água projetado com tecnologia avançada IP68 que permite que você lave as mãos, tome banho e esportes aquáticos. Baixe e instale o aplicativo gratuito \" Da Fit\", ele sincronizará com seu telefone instantaneamente</li><li>Funcionalidades de Mensagens e Redes Sociais: O relógio possibilita a leitura de mensagens de plataformas como WhatsApp, Facebook, Twitter, entre outras. No entanto, não oferece a capacidade de responder a essas mensagens. Além disso, ele exibe notificações de redes sociais diretamente na tela do dispositivo</li><li>Contém: caixa de presente、carregador magnético、manual do usuário, garantia de dois meses</li><li>Champagne ouro</li><li>Cinza</li><li>Ouro rosê</li><li>Prata</li><li>Preto</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Masculino-Smartwatch-Inteligente-Bluetooth-Exerc%C3%ADcio/dp/B0F6D2CWS7?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B072MTS8VQ",
    "title": "Hidratante e Calmante sem Fragrância para Pele Muito Sensível/Sensibilizada dos Bebês e Crianças, Mustela Bebê, Rosa, Médio/200 ml",
    "image": "https://m.media-amazon.com/images/I/51OPWF9W34L._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 71.08,
    "price_original": 105.81,
    "parcelamento": "Em até 12x de R$ 6,56 com juros",
    "tem_selo_prime": false,
    "avaliacao": 4.9,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "<ul><li>Com ação calmante e sem fragrância, hidrata de forma imediata e prolongada, graças aos ativos naturais</li><li>Acalma a pele irritada e muito sensível/sensibilizada, deixando a pele macia e suave, melhorando a sensação de desconforto e irritação, graças ao ativo natural e patenteado schizandra</li><li>Reforça e restaura a barreira cutânea e preserva a riqueza celular da pele, graças ao ativo natural patenteado perseose de abacate</li><li>Textura leve e suave, de rápida absorção</li><li>Hipoalergênico e alta tolerância</li><li>Testado e recomendado por pediatras e dermatologistas; com ativos naturais e patenteados</li><li>Com ação calmante e sem fragrância, hidrata de forma imediata e prolongada, graças aos ativos naturais</li><li>Acalma a pele irritada e muito sensível/sensibilizada, deixando a pele macia e suave, melhorando a sensação de desconforto e irritação, graças ao ativo natural e patenteado schizandra</li><li>Reforça e restaura a barreira cutânea e preserva a riqueza celular da pele, graças ao ativo natural patenteado perseose de abacate</li><li>Textura leve e suave, de rápida absorção</li><li>Hipoalergênico e alta tolerância</li><li>Testado e recomendado por pediatras e dermatologistas; com ativos naturais e patenteados</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Hidratante-Calmante-Fragrncia-Sens%C3%ADvel-Sensibilizada/dp/B072MTS8VQ?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  },
  {
    "asin": "B0FVGCV1C2",
    "title": "Mala de Bordo 10kg Mochila Bagagem de Mão com 4 Rodas Duplas 360° | Mala de Viagem, Expansivel, Aprovada ANAC, Cadeado AntiFurto TSA, Alça Lateral, com Divisória, Leve, Resistente",
    "image": "https://m.media-amazon.com/images/I/51FPN9OYKYL._AC_SL1000_.jpg",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 341.06,
    "price_original": 398.9,
    "parcelamento": "ou R$ 341,06 em até 6x de R$ 56,86 sem juros",
    "tem_selo_prime": false,
    "avaliacao": 4.5,
    "qtd_avaliacoes": null,
    "coupon_code": null,
    "description": "<ul><li>Kit ideal para viagens com mais praticidade e mobilidade — O conjunto Vaceli acompanha mala de bordo e mochila de viagem expansível, oferecendo uma combinação versátil para quem busca organização, conforto e eficiência em viagens curtas, médias ou na rotina do dia a dia.</li><li>Mala rígida em ABS com resistência e segurança — Produzida em ABS rígido, a mala proporciona estrutura leve, durável e resistente a impactos, além de contar com rodas duplas com giro 360°, alça lateral ergonômica e cadeado TSA antifurto integrado para mais proteção durante o transporte.</li><li>Tamanho ideal para cabine e embarque prático — A mala de bordo é aprovada pela ANAC para até 10kg, sendo ideal para levar na cabine e evitar custos extras com despacho, trazendo mais agilidade no embarque e mais liberdade para viajar com praticidade.</li><li>Mochila com excelente organização interna — A mochila foi desenvolvida para oferecer conforto e funcionalidade, com compartimento para notebook, divisórias internas e zíper reforçado, facilitando o transporte de eletrônicos, documentos, roupas e itens pessoais com mais segurança.</li><li>Design moderno para viajar com estilo e conforto — O Kit Vaceli une elegância, funcionalidade e acabamento moderno, sendo uma escolha ideal para quem deseja viajar com mais confiança, organização e praticidade em qualquer destino.</li><li>Kit ideal para viagens com mais praticidade e mobilidade — O conjunto Vaceli acompanha mala de bordo e mochila de viagem expansível, oferecendo uma combinação versátil para quem busca organização, conforto e eficiência em viagens curtas, médias ou na rotina do dia a dia.</li><li>Mala rígida em ABS com resistência e segurança — Produzida em ABS rígido, a mala proporciona estrutura leve, durável e resistente a impactos, além de contar com rodas duplas com giro 360°, alça lateral ergonômica e cadeado TSA antifurto integrado para mais proteção durante o transporte.</li><li>Tamanho ideal para cabine e embarque prático — A mala de bordo é aprovada pela ANAC para até 10kg, sendo ideal para levar na cabine e evitar custos extras com despacho, trazendo mais agilidade no embarque e mais liberdade para viajar com praticidade.</li><li>Mochila com excelente organização interna — A mochila foi desenvolvida para oferecer conforto e funcionalidade, com compartimento para notebook, divisórias internas e zíper reforçado, facilitando o transporte de eletrônicos, documentos, roupas e itens pessoais com mais segurança.</li><li>Design moderno para viajar com estilo e conforto — O Kit Vaceli une elegância, funcionalidade e acabamento moderno, sendo uma escolha ideal para quem deseja viajar com mais confiança, organização e praticidade em qualquer destino.</li><li>Material ABS rígido  – leve, durável e resistente a impactos</li><li>Rodas duplas 360° e cadeado TSA antifurto integrado</li><li>Aprovada pela ANAC  – ideal para cabine e viagens práticas</li><li>Mochila expansível incluída  com compartimentos funcionais</li><li>Design Vaceli  – elegância, conforto e praticidade em cada viagem</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Expansivel-Aprovada-AntiFurto-Divis%C3%B3ria-Resistente/dp/B0FVGCV1C2?tag=mixdm22-20",
    "last_checked_at": "2026-07-17T18:35:23.000Z",
    "spotlight": false
  }
];
